### PR TITLE
Community tasks (Issue #1280): add PR template.

### PR DESCRIPTION
**Pull request by nalyd88**
First try at PR template.

### CODE REVIEW

**Comment by chfast** [comment]
Personally, I don't like these.

**Comment by ddobreff** [comment]
I am with @chfast on this.

**Comment by StefanOberhumer** [comment]
I like the style whow this project handles PR - so I think I will/would not use in 99% of my PRs.
Result: **I'm also with @chfast**
But I've to say - I like the issue template - as I hope (and sometimes already happens) we're getting better issue reports!

**Comment by jean-m-cyr** [comment]
This could be pared down to:
- Description
- How to reproduce
- Environment

**Comment by nalyd88** [comment]
So, no PR template or a different one? If no on the PR template is there anything left on this issue?

**Comment by jean-m-cyr** [comment]
No apparent support for this... closing

**Pull request closed without merging**
