### PR TITLE
May have to revert PR1967, passes CI but breaks master!

### PR DESCRIPTION
**Pull request by jean-m-cyr**

### CODE REVIEW

**Comment by AndreaLanfranchi** [comment]
What do you mean by "breaks master" ?
I have a similar environment and compiles fine locally.
The only thing you have to take care of (after changing hunter release) is to delete .hunter cache folder (and let rebuild all from scratch).

**Comment by AndreaLanfranchi** [comment]
Oh I see. You need also to upgrade Boost to 1.70+
On my env it works with 
```
hunter_config(Boost VERSION 1.70.0-p0)
```
set in https://github.com/ethereum-mining/ethminer/blob/master/cmake/Hunter/config.cmake

But I reckon there's some additional work to do as some methods used in the project to get th IO_SERVICE are deprecated in 1.70

**Comment by slashbinslashnoname** [comment]
Is it possible to review it ? 
In order to add a last breath to 4gb mining hardware :) 
https://github.com/ethereum-mining/ethminer/pull/1998

**Comment by jean-m-cyr** [comment]
In that case, I think we should just revert and call it good enough.

**Comment by jean-m-cyr** [comment]
@AndreaLanfranchi Since I can't merge my own PRs, can you approve and merge this. Like I do, I imagine you take some pride in what was achieved with this project. With this last merge, ready for one final release to close this last chapter of what has been a sometimes bumpy but interesting adventure.

**Comment by AndreaLanfranchi** [comment]
Thank you for the honor. I appreciate it.
Interesting times working together.

**Comment by AndreaLanfranchi** [comment]
This is the final milestone. Many thanks to:
@chfast 
@jean-m-cyr 
@ddobreff 
@StefanOberhumer 
@MariusVanDerWijden 
And all the others who contributed in these years.
I believe Pawel will make a final release

**Pull request merged**
