### PR TITLE
More farm refactoring

### PR DESCRIPTION
**Pull request by jean-m-cyr**

### CODE REVIEW

**Comment by jean-m-cyr** [comment]
@AndreaLanfranchi Completely agree. Go for it! Untangle that mess...

**Comment by AndreaLanfranchi** [comment]
> On the other hand Miner->Farm->PoolManager->Client makes sense architecturally...

Can't agree. The "farm" step is actually completely unuseful. It's only a placeholder to dinamically attach a function which is already owned by PoolManager.
Function which is set to a complete void only in benchmark mode.

My goal is to remove an unuseful thread crossing (miner has it's own, farm has it's own, poolmanager has it's own, client lives in the same thread of poolmgr)

**Comment by AndreaLanfranchi** [comment]
On the other hand the singleton pattern you have worked on is exactly meant to remove unneded references and steps which were mandatory when there was no direct visibility among "services".

**Comment by jean-m-cyr** [comment]
Ok, but there is no thread crossing in the Miner->Farm->PoolManager->Client path. I agree that the Farm bridge does nothing!

**Pull request merged**
