### PR TITLE
Clean up command line arguments processing

### PR DESCRIPTION
**Pull request by jean-m-cyr**

### CODE REVIEW

**Comment by AndreaLanfranchi** [comment]
Is it me missing something or we do loose some sanity checks over entered values ?
For example that --tstop must be ge than --tstart ...

**Comment by jean-m-cyr** [comment]
@AndreaLanfranchi The check can only occur after the parse, but it is included below.

**Comment by AndreaLanfranchi** [comment]
Sorry ... I was totally missing that.

**Comment by jean-m-cyr** [comment]
There is very little left in main.cpp! Should I combine main.cpp and Mineraux.h into a single file. There are no other includes of Mineraux.

**Comment by AndreaLanfranchi** [comment]
Good idea. 
Worth it to have 2 files with single name: a proper header and a proper code file. (one .h and one .cpp)
IMHO

**Comment by jean-m-cyr** [comment]
I was thinking a single main.cpp file. MinerAux.h is only included by main.cpp so it is not the typical header file. It contains mostly executable code and no common (shared) variables. It is strictly for main.cpp's use, so why not just include it as part of main.cpp instead of #including it as a separate file?

**Comment by AndreaLanfranchi** [comment]
Mine was only a suggestion due to personal habit ... wether there is a class (MinerCLI is) I prefer to have definition into .h and executable code in .cpp 
But it's only cosmetic and I reckon It might involve some additional lines to write definitions.

**Comment by jean-m-cyr** [comment]
There is no consistency in that respect in Ethminer. Some seem to prefer .h only formulation with executable code inline, others as you say with separate header and executable components. I'll adapt to whatever style is currently in use.

**Comment by AndreaLanfranchi** [comment]
@jean-m-cyr could you please add in help text the meanings for stratumx+tcp modes ?
Since we've dropped -SP argument we have also dropped the description and now people do not understand whether to use stratum or stratum1 or stratum 2

```
        0: official stratum spec: ethpool, ethermine, coinotron, mph, nanopool (default)
        1: eth-proxy compatible: dwarfpool, f2pool, nanopool (required for hashrate reporting to work with nanopool)
        2: EthereumStratum/1.0.0: nicehash
```

**Pull request merged**
