### PR TITLE
Add info about modified response of miner_getstathr API call.

### PR DESCRIPTION
**Pull request by StefanOberhumer**
Update documentation to match change 6df515edaec6ff1604ddee579851751b0b5329cd .

### CODE REVIEW

**Comment by AndreaLanfranchi** [comment]
@StefanOberhumer ... as you're on the topic could you please add "ethminer " in all json members which report version ?

Thank you !

**Comment by StefanOberhumer** [comment]
@AndreaLanfranchi 

> @StefanOberhumer ... as you're on the topic could you please add "ethminer " in all json members which report version ?

Should I create an explicit PR ?

**Comment by AndreaLanfranchi** [comment]
No ... it's minor adjustment. 
Can integrate this one.

**Comment by StefanOberhumer** [comment]
> No ... it's minor adjustment.
> Can integrate this one.

... I was too slow ... :-)

**Pull request merged**
