### PR TITLE
Apparently 16 is not enough! Increase and parameterize max # of GPUs

### PR DESCRIPTION
**Pull request by jean-m-cyr**
Set maximum number of GPUs supported to 32

### CODE REVIEW

**Comment by DeadManWalkingTO** [comment]
LOL <3

**Comment by jean-m-cyr** [comment]
@chfast Does a link to the current master CI merge build products exist?

**Comment by shtinkov** [comment]
I can confirm that this commit works perfect with 18 cards

**Comment by jean-m-cyr** [comment]
@shtinkov Thanks

**Pull request merged**
