### PR TITLE
URGENT patch. Fix bad merge.

### PR DESCRIPTION
**Pull request by jean-m-cyr**
I accidentally pushed and merged a wrong piece of
the cuda merge and broke the image. Actually pushed
the right branch... from the wrong system.

This reverts this bonehead move on my part, leaving
a working merged cuda miner intact.

My apologies to all.

### CODE REVIEW

**Comment by jean-m-cyr** [comment]
@MariusVanDerWijden Thanks

**Comment by jramos** [comment]
Ran overnight and got minimal stales on ethermine.

**Comment by jramos** [comment]
Before:
before

After:
after

**Comment by jean-m-cyr** [comment]
@jramos Definitely looks better

**Comment by jramos** [comment]
Indeed. Very consistent now. Much appreciated.

holding steady

**Pull request merged**
