### PR TITLE
macOS patch

### PR DESCRIPTION
**Pull request by sowson**
Those changes make the possibility to run on macOS, thanks!

### CODE REVIEW

**Review by jean-m-cyr — COMMENTED** [review]
MAC OS is not supported, nor will I introduce unknown hunter repo/

**Comment by sowson** [comment]
Thank you for the feedback, I keep it only on my fork in case someone wanted to try it. Appreciate!

**Comment by levyfan** [comment]
@sowson got "Socket write failed : Operation not permitted" on this patch, even run as sudo, not sure what happened. Could you help me find what is going on?

```
 i 15:44:26          Configured pool stratum.okpool.me:3336
 i 15:44:26          Selected pool stratum.okpool.me:3336
 X 15:44:26          Socket write failed : Operation not permitted
 i 15:44:26          Connection remotely closed by stratum.okpool.me
 i 15:44:26          Disconnected from stratum.okpool.me:3336
 i 15:44:26          No connection. Suspend mining ...
SIGSEGV encountered ...
```

**Comment by httphaul** [comment]
@sowson

ethminer is crashing after 'Creating mining buffer'. 

Tested and failed on the following systems: amd rx5500 bigsur 11.3 and amd rx6800xt big sur 11.4

Thanks in advance.

Screen Shot 2021-05-19 at 2 07 23 PM

**Pull request closed without merging**
