### PR TITLE
Use cl2.hpp instead of cl.hpp

### PR DESCRIPTION
**Pull request by EoD**
Currently platform detection is "broken", because cl.hpp uses different
platform name strings (with "\0") while cl2.hpp does not.

This PR does not delete ``cl.hpp``. Should it?

**This should only be merged if the warnings mentioned in #216 are acceptable!**

### CODE REVIEW

**Comment by EoD** [comment]
There are even more (OpenCL 1.1) deprecation warnings on MacOS: https://travis-ci.org/ethereum-mining/ethminer/jobs/264148967

We could go to ``CL_HPP_MINIMUM_OPENCL_VERSION = 120`` instead of ``CL_HPP_MINIMUM_OPENCL_VERSION = 110``. In the case of Mesa/Clover, this still seems to be fine.

**Comment by chfast** [comment]
Ok, delete the cl.hpp and try `CL_HPP_MINIMUM_OPENCL_VERSION = 120`.

**Comment by EoD** [comment]
I added ``CL_HPP_MINIMUM_OPENCL_VERSION = 120`` and deleted ``cl.hpp``.

**Comment by chfast** [comment]
Merged in https://github.com/ethereum-mining/ethminer/commit/a16c582d2cc14bbd9cdb2ab04ada4c1b98a508b5.

**Pull request closed without merging**
