### PR TITLE
Add Volta Support

### PR DESCRIPTION
**Pull request by rcldesign**
adds support for NVIDIA Volta GPU's

### CODE REVIEW

**Comment by rcldesign** [comment]
Failed CI because this change requires newer versions of nvcc. I tested with 9.x which worked just fine.

**Comment by chfast** [comment]
I think you have to upgrade CI config to use CUDA 9 instead of 8.

**Comment by chfast** [comment]
I upgraded CUDA on Travis to 9.0

**Comment by chfast** [comment]
Hello?

**Comment by rcldesign** [comment]
Hi - not sure what to do now to get the CI to run again. Do I need to
submit another pull request?

**Comment by chfast** [comment]
You have to do git rebase of this branch.

**Comment by chfast** [comment]
Replaced by #404.

**Pull request closed without merging**
