### PR TITLE
Specify utf-8 char set in http header

### PR DESCRIPTION
**Pull request by jean-m-cyr**

### CODE REVIEW

**Comment by StefanOberhumer** [comment]
@jean-m-cyr 
Just for my (personal) info: Does that mean gethostname() returns an utf-8 string(even under windows) and/or does "stringstream <<" interprets char as utf-8 encoded ?
Simplifying my question: Why are we sure all strings encoded utf-8 ?

**Comment by StefanOberhumer** [comment]
@jean-m-cyr :  BTW: Thanks caring about this topic.

**Comment by jean-m-cyr** [comment]
@StefanOberhumer idk... All my systems as set up to use utf-8 by default. Is it possible to force all ethminer inputs to be utf-8?

**Comment by chfast** [comment]
You can try this https://github.com/ethereum-mining/ethminer/issues/197.

**Pull request merged**
