### PR TITLE
Update ethash

### PR DESCRIPTION
**Pull request by chfast**

### CODE REVIEW

**Comment by AndreaLanfranchi** [comment]
Sorry if my question may sound suspicious.
Which are the implications of subproject "ethash" licensed under Apache 2.0 vs ethminer under GPL V3 ?
Am I wrong or there is an one direction incompatibility ? 

Just want to understand how our work is going to be dependant on other sources, even if I reckon ethash is mantained by @chfast

**Comment by jean-m-cyr** [comment]
@AndreaLanfranchi Depends who you ask! FSF says no, Apache says yes...

**Comment by chfast** [comment]
I believe as long ethminer uses ethash (not other way around) this is fine. LLVM (BSD-like license) wanted to switch to Apache 2 and they confirmed that still LLVM libraries would be allowed to be included in GPL projects.

**Comment by AndreaLanfranchi** [comment]
Thank you for explanation.
Mergeable for me.

**Pull request merged**
