### PR TITLE
Reduce count of XOR operations at theta step of keccak

### PR DESCRIPTION
**Pull request by KGusev**
Theta step of keccak contains duplicate calculation of **xor** operation. Often it is manifested as sequence of **xor3** calls in which second and third arguments don't changing during these calculations. Therefore **xor** of second and third argument can be calculate in advance

### CODE REVIEW

**Comment by jean-m-cyr** [comment]
I would expect any half-decent compiler to automatically recognize and implement this type of obvious optimization.

**Comment by AndreaLanfranchi** [comment]
Worth trying an instrument measurement ?

**Comment by jean-m-cyr** [comment]
Doing it now

**Comment by jean-m-cyr** [comment]
The before and after results here are pretty much identical. However, I don't oppose the merging of this PR as it actually better illustrates in code what is going on.

**Comment by AndreaLanfranchi** [comment]
Thank you @jean-m-cyr.
Will you take the honor to approve ?

**Pull request merged**
