### PR TITLE
added support for __shfl_sync since __shfl is deprecated with CUDA 9.0

### PR DESCRIPTION
**Pull request by MariusVanDerWijden**
Added support for the __shfl_sync since __sfhl is deprecated in CUDA 9.0
**This is up for testing**
It's mostly just syntactical change but review it anyway

### CODE REVIEW

**Comment by MariusVanDerWijden** [comment]
We can use __activemask() in the shuffle operations, to only send to all active warps, but i think 0xFFFFFFFF (send to all warps is probably faster (one less library call)

**Comment by smurfy** [comment]
First of, thanks for contributing, since i'm no cuda expert i cant say anything about this, but is there an improvement regarding speed with this changes or is it basically just to get rid of the deprecation warning and make the code future proof?

**Comment by MariusVanDerWijden** [comment]
It's mostly aesthetic, but using CUDA 9 can show significant improvements, since branching isn't such an performance hit, as with CUDA 8. Also most of my changes are in the generation of the DAG, which is only triggered sometimes, so it won't make any real improvement to mining, especially on Cards < Volta, on these cards the mask is ignored... It may however make a change in Volta cards, but i don't even own a CUDA-GPU, so testing is pretty hard for me :)

**Comment by chfast** [comment]
Can't we use __shfl_sync also for CUDA < 9?

**Comment by MariusVanDerWijden** [comment]
No, it throws an error:
error: identifier "__shfl_sync" is undefined
while compiling with CUDA 8.0
Btw,
__shfl_sync is supported by devices of compute capability 3.x or higher.

**Pull request merged**
