### PR TITLE
API: Implement miner_reboot().

### PR DESCRIPTION
**Pull request by StefanOberhumer**

### CODE REVIEW

**Comment by StefanOberhumer** [comment]
@ ddobreff : I'll prepare internally - but will not put it in the API at this time:
* API call `miner_reboot` is a known call in some other mining software (so I'd like to activate it to support some monitoring tools)
* I personally needs the `farm.reboot()` in future (I'm writing on a watchdog task)

**Comment by jean-m-cyr** [comment]
Sorry, tried to fix windows compile... didn't work!

**Comment by StefanOberhumer** [comment]
@jean-m-cyr Thanks for your help.
I'll try to set up a windows compile framework next week to check my changes before making a PR  (long on my todo list).
I'm pleased if you find a solution in the meantime - so don't be afraid to try some ideas.

**Comment by AndreaLanfranchi** [comment]
Hi all,
I've not seen the whole code yet but wanted to share a thought. Why focus 
on the execution of a particular bat/bash instead of setting a well defined 
exit code ?
I believe 99.9 of ethminer instances are already wrapped in a script where 
you can easily handle exit codes and take action accordingly. this way you 
don't have to bother with different compile rules for Windows or Linux.
I'd rather focus on ways to clean exit from ethminer when, for example, we 
have PCI errors.

My two cents


Sent from mobile. Apologies for brevity and typos.

In data 11 agosto 2018 23:59:07 Stefan Oberhumer <notifications@github.com> 
ha scritto:

**Comment by StefanOberhumer** [comment]
Sometimes I can not stop ethminer using `kill` or CTL+C.
Rebooting would be just the last possibility.

**Comment by AndreaLanfranchi** [comment]
If ethminer doesn't respond to os signals then reboot will not function 
either as Linux will try to close processes clean. At least this is my 
experience. Only a cold restart (power off) may work


Sent from mobile. Apologies for brevity and typos.

In data 12 agosto 2018 12:54:29 Stefan Oberhumer <notifications@github.com> 
ha scritto:

**Comment by StefanOberhumer** [comment]
@AndreaLanfranchi At this rare moments I try
`echo 1 > /proc/sys/kernel/sysrq; echo b > /proc/sysrq-trigger`
which initiates a boot (I know this is really a brutal method - not syncing, no process stopped, can end up in destroyed filesystem - for this reason I put all my logs on a tmpfs)

**Comment by AndreaLanfranchi** [comment]
Yes that simulates a power cycle but it works only being root. Also echoing 
with sudo apparently does not work


Sent from mobile. Apologies for brevity and typos.

In data 12 agosto 2018 13:27:28 Stefan Oberhumer <notifications@github.com> 
ha scritto:

**Comment by StefanOberhumer** [comment]
> ...Also echoing with sudo apparently does not work

I just use sudo a script that do the two echos. That works !

**Pull request merged**
