### PR TITLE
hashrate reporting fix

### PR DESCRIPTION
**Pull request by vatanuki**
hashrate reporting fix

### CODE REVIEW

**Comment by lordrive** [comment]
It's not working, i tried your build and the hashrate reporting is still stopped after 30 mins. (in my case)

**Comment by vatanuki** [comment]
its working on 3 rigs for 10 hours already (Nvidia @ WIN10) - and all is ok till now, also my local testing build has debug outputs in case there are other problem that is not fixed by this patch, so im still watching

**Comment by lordrive** [comment]
I have a rig with 3 rx 570 and it took 30 mins for it to stop reporting the hashrates
kep

**Comment by vatanuki** [comment]
can u check was it reporing issue (not sending data to pool) or it was hashrate calc issue (rate 0 was submitted) ?

**Comment by lordrive** [comment]
It was sending other data correctly, only the hashrate reporting stopped completely, not even 0 was submitted.

**Comment by invidtiv** [comment]
I have the same issue in some rigs, I have concluded that it is a dns error that originates this condition, for the work it recover and reconnects, however the reporting never comes back online.
It is hard to detect but if you pull the ethernet plug , for 5 seconds, you can replicate the error.
Hope that these notes are able to aid.

**Comment by kalltkaffe** [comment]
Been running this fix for almost 25 hours now and it still reports hashrate just fine. I also tried pulling the network cable for 5 seconds as suggested above but it did not reintroduce the problem.
image

**Comment by vatanuki** [comment]
just stopped reporting (after 2+ days), still need to work on this bug

**Comment by vatanuki** [comment]
> @lordrive lordrive commented 2 days ago
> It was sending other data correctly, only the hashrate reporting stopped completely, not even 0 was submitted.

will u try new fix?

**Comment by lordrive** [comment]
Sure, i'll start testing it now.  @vatanuki

**Comment by lordrive** [comment]
The first gap is probably when i started the new miner build, but i have no idea what is the second gap. But i'll keep it running to see what happens. 
kep

**Comment by vatanuki** [comment]
got new issue when main thread stop sending to startum after connection problems and

> Exception thrown in Worker thread: invalid vector<T> subscript

**Comment by lordrive** [comment]
Bad news:
kep

**Comment by vatanuki** [comment]
> @lordrive commented 17 hours ago
> Bad news:

w/o any errors in console?

**Comment by lordrive** [comment]
Yup. It continued mining just the reports stopped.

**Comment by vatanuki** [comment]
> @lordrive commented a day ago
> Yup. It continued mining just the reports stopped.

try with additional fix #3 and can u copy console log, not all just around ~2 min on stop reporting time

**Comment by kolumbus120** [comment]
with 0.14.rc0 on etc.ethermine.org after 20min. stop reporting hashrate.
it was strautm+ssl
hashrate

**Comment by elmamut** [comment]
@kolumbus120 work fine for me +3h

ethminer.exe --farm-recheck 200 --report-hashrate -HWMON -G -F http://....../ --cl-local-work 128 --cl-global-work 8192

**Comment by vatanuki** [comment]
> @kolumbus120 commented 7 hours ago •  edited 
> with 0.14.rc0

rc0 ? or rc0 + this fix? where did u get executable?

**Comment by kolumbus120** [comment]
> @vatanuki 
> rc0 ? or rc0 + this fix? where did u get executable?

It was just rc0. I thought that reported hashrate (this fix) is already in rc0.
I executed this:
ethminer.exe --farm-recheck 200 -U -P stratum+tcp://xxxx@eu1-etc.ethermine.org:14444 -RH --cuda-block-size 256 --cuda-grid-size 8192 --cuda-streams 2 --cuda-parallel-hash 4

**Comment by vatanuki** [comment]
> @kolumbus120 commented an hour ago
> 
> It was just rc0. I thought that reported hashrate (this fix) is already in rc0.

 no, fix is in pull requests and is not in Releases yet

@lordrive and where u get executable? in Releases too?

i have 2+ days working fine

**Comment by lordrive** [comment]
@vatanuki from here https://ci.appveyor.com/project/ethereum-mining/ethminer/history

**Comment by vatanuki** [comment]
@jean-m-cyr this is not revert, EthStratumClient::submitHashrate is separate from EthStratumClient::submitSolution (not a same thread, checked by thread id) or what do you mean?

**Comment by jean-m-cyr** [comment]
Did I miss something? There is all the normal stratum io handled in EthStratum, but submitHashrate is called by another thread (I think its from either the main thread, or the pool manager thread). So effectively you've got concurrent use of the SSL socket by two independent threads.

**Comment by vatanuki** [comment]
@jean-m-cyr what about this part? does not it split threads?

```javascript
m_hashrate_event.expires_from_now(boost::posix_time::milliseconds(100));
m_hashrate_event.async_wait(boost::bind(&EthStratumClient::hashrate_event_handler, this, boost::asio::placeholders::error));
```

i did not look at other socket code, how it should work (the idea) ?

**Comment by jean-m-cyr** [comment]
Ah, ok. Good.

**Comment by piotr-dobrogost** [comment]
Could we have a few words of summary? Is socket accessed from one thread now? How is it enforce?

**Comment by vatanuki** [comment]
i cant tell for sure, its first time i meet "asio" but from what i read it uses same thread pool

```javascript
m_worktimer(m_io_service),
...
m_hashrate_event(m_io_service),
...
m_socket = new boost::asio::ip::tcp::socket(m_io_service);
```

docs: [io_service.thread_safety](http://www.boost.org/doc/libs/1_46_1/doc/html/boost_asio/reference/io_service.html#boost_asio.reference.io_service.thread_safety)

**Comment by jean-m-cyr** [comment]
With this PR it is presently accessed by a single thead, the ethstratum's io_service thread.

**Comment by piotr-dobrogost** [comment]
I started version b9dd182 and it's been reporting 0 hashrate from the beginning.

**Comment by akostadinov** [comment]
For me these settings with `--cl-global-work 1048576 --cl-local-work 256` reports above 130MH/s on Vega FE while actual pool hash rate appears ~13MH/s. `--cl-global-work 524288 --cl-local-work 256` shows 66MH/s while actual differs. There is something broken with reporting still.

--  **0.15.0.dev0+git.26a51df**

**Pull request merged**
