### PR TITLE
Experimental OpenCL kernel. 2x hashrate on Mac Pro with D500 GPUs

### PR DESCRIPTION
**Pull request by wtfuzz**
Unrolled DAG RAM mixing in a single thread, rather than spreading the mixer across 8 threads.

### CODE REVIEW

**Comment by andrusha** [comment]
This branch:
```
min/mean/max: 2097152/2376772/2446677 H/s
inner mean: 815559 H/s
```
vs

Master:
```
min/mean/max: 17476266/17476266/17476266 H/s
inner mean: 0 H/s
```

Running on Ubuntu 16.04 and Tesla M60.

**Comment by wtfuzz** [comment]
So far improvements have only been reported on macOS OpenCL

**Comment by chfast** [comment]
Somehow Nvidia decided to break its OpenCL on Linux, so I cannot test it at the moment.

**Comment by fake666** [comment]
i just tested this on my mac pro with dual firepro d500:

current master:
min/mean/max: 6891639/6932538/6990506 H/s
inner mean: 6926849 H/s

with this patch:
min/mean/max: 14665398/14677130/14680064 H/s
inner mean: 4893354 H/s

yay :D

**Comment by pnomolos** [comment]
Just tested on an Ubuntu 16.04 box with a Radeon Fury X:

```
[OPENCL]:Using platform: AMD Accelerated Parallel Processing
[OPENCL]:Using device: Fiji(OpenCL 1.2 AMD-APP (2348.3))
[OPENCL]:/tmp/OCL29891T3.cl:303:37: error: variables in function scope cannot be declared static
  __local static compute_hash_share share[GROUP_SIZE];
                                    ^
/tmp/OCL29891T3.cl:304:24: error: variables in function scope cannot be declared static
  __local static mix_t mix[GROUP_SIZE];
                       ^
2 errors generated.

error: Clang front-end compilation failed!
Frontend phase failed compilation.
Error: Compiling CL to IR

[OPENCL]:clEnqueueWriteBuffer(-38)
```

**Comment by dbvrac** [comment]
@fake666 Did you make any further code/config tweaks? I'm still getting:
min/mean/max: 6640981/6710885/6728362 H/s inner mean: 2242787 H/s
 - Mac Pro, dual D700's

**Comment by fake666** [comment]
@dbvrac no, maybe it's specific to D500s? no idea ¯\_(ツ)_/¯

**Comment by dbvrac** [comment]
OPENCL#0: 6%
[OpenCL] Printing program log
[OpenCL] <program source>:324:9: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
                if (i == thread_id)
      ~ ^  ~~~~~~~~~
<program source>:359:9: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
                if (i == thread_id)
      ~ ^  ~~~~~~~~~

[OpenCL] Creating cache buffer
[OpenCL] Creating DAG buffer
[OpenCL] Loading kernels
[OpenCL] Writing cache buffer
OPENCL#0: 8%

--Mac Pro D700

**Comment by akiatoji** [comment]
A couple of more data points:

AMD Radeon Pro 460 (2016 MBP)
```
min/mean/max: 1571816/1641674/1659139 H/s  inner mean: 553046 H/s
```
vs
```
min/mean/max: 3923006/3997022/4016863 H/s inner mean: 2676127 H/s
```


Sapphire RX580 (eGPU)
```
min/mean/max: 4366155/4436607/4454963 H/s inner mean: 2969480 H/s
```
vs
```
min/mean/max: 11155063/11201116/11268435 H/s  inner mean: 11194027 H/s
```

**Comment by dbvrac** [comment]
(3) Mac Pro 2013's:
min/mean/max: 22840614/22977385/23060985 H/s  inner mean: 22995108 H/s
2 machines compile and run, then slow to 0Mh/s
1 machine wont compile (need to find that hunter/boost fix), but binary compiled from another machine is stable.

**Comment by EoD** [comment]
When I fix the issues from @pnomolos above, I get the following results

```
[OPENCL]:Using platform: Clover
[OPENCL]:Using device: AMD Radeon R9 380 Series (AMD TONGA / DRM 3.10.0 / 4.11.8-gentoo, LLVM 3.9.1)(OpenCL 1.1 Mesa 17.2.0-devel (git-038c45a40e))
```

[New kernel](https://github.com/wtfuzz/ethminer/blob/4a498657df8618cad674b215ff1ae6037631858d/libethash-cl/ethash_cl_miner_kernel.cl):
```
Trial 1... 6815744
Trial 2... 6640981
Trial 3... 6640981
Trial 4... 6815744
Trial 5... 6640981
min/mean/max: 6640981/6710886/6815744 H/s
inner mean: 2271914 H/s
```


[Old kernel](https://github.com/EoD/ethminer/blob/608c51f0cb1f57659aae7c67e676a02cb1ecc403/libethash-cl/ethash_cl_miner_kernel.cl):
```
Trial 1... 7340032
Trial 2... 7514794
Trial 3... 6116693
Trial 4... 7514794
Trial 5... 6116693
min/mean/max: 6116693/6920601/7514794 H/s
inner mean: 4951608 H/s
```

**Comment by dbvrac** [comment]
I have it running great on all machines. Oddly enough, I solved the 'drop to 0MH/s' problem by resetting the sleep to 'never' in Energy Saver. Still wont compile clean on one machine, but I'm sure that's my oversight somehow.

**Comment by mxjoe** [comment]
wtfuzz I tried your changes on an iMac 2017 with Radeon Pro 580 (macOS 10.12.6) and the hashrate nearly doubled from around 5 MH/s to 10 MH/s, thanks man, great job!
Is there a way to increase the hashrate under macOS even further? Under Windows 10 the same machine achieves 19,5 MH/s.

**Comment by mxjoe** [comment]
When will this pull request go into ethereum-mining/ethminer master? Is there something I can do besides confirming that it boosts hashrate on several Macs (Radeon Pro 460, D700 and Radeon Pro 580)?

**Comment by chfast** [comment]
In this form -- never. Read the comments above.

**Comment by mxjoe** [comment]
@chfast You mean because you cannot test it with you nVidia card under linux, right? I understand this.
nVidia released an updated driver yesterday, maybe [this one](http://www.nvidia.com/download/driverResults.aspx/123103/en-us) fixed the bug.

**Comment by chfast** [comment]
No. This patch number of parallel hashes from 8 to 1. This works better for some GPUs, but worse for others. What is needed here is an command line switch that controls the number, similar to `--cuda-parallel-hashes`.

Without this, the change would degrade performance for many users. I can test it on 280x, and the hashrate is much lower.

**Comment by mxjoe** [comment]
I understand, thanks for your detailed explanation.

**Comment by smurfy** [comment]
Differences should be visible on Windows too right?,  So maybe i can do some test with and without the patch on windows. (And a RX 580)

Since there are more changes than just decreasing the number of threads. (Loop completely removed, i do not really understand what the cl code is doing in the loop) It should be easy to do comparisons between the speed with this pr,  default and default but threadcount to 1.  

If PR and threadcount to 1 gives the same values it is probably fairly simple to make the threadcount configurable. @mxjoe can you see a gain with this patch or was your request to merge mainly because you thought its a general improvement for all cards.

Neverless, the PR also looks a bit like an edge case for me.  (mac pro is not considered the top choice as a mining platform for me :))

**Comment by mxjoe** [comment]
@smurfy With wtfuzz's changes the hashrate on all tested Macs (MacBook Pro, MacPro, iMac) with different GPUs (Radeon Pro 460, Radeon Pro 580, FirePro D700) nearly doubled. An example is the Radeon Pro 580 which achieves about 10 MH/s with the patch and 5 MH/s without (under macOS 10.12.6). Under Windows 10 with Claymore Dual Miner it is even 20 MH/s.

**Comment by chfast** [comment]
Maybe this is related to the macOS's OpenCL implementation. If yes, we can enable this for macOS only.

**Comment by chfast** [comment]
@wtfuzz Can you rebase this?

**Comment by ddobreff** [comment]
I can confirm that it doesn't work on linux:

> [OPENCL]:/tmp/OCL16106T5.cl:303:37: error: variables in function scope cannot be declared static
  __local static compute_hash_share share[GROUP_SIZE];
                                    ^
/tmp/OCL16106T5.cl:304:24: error: variables in function scope cannot be declared static
  __local static mix_t mix[GROUP_SIZE];
                       ^
2 errors generated.

error: Clang front-end compilation failed!
Frontend phase failed compilation.
Error: Compiling CL to IR

[OPENCL]:clEnqueueWriteBuffer(-38)
[OPENCL]:/tmp/OCL16106T7.cl:303:37: error: variables in function scope cannot be declared static
  __local static compute_hash_share share[GROUP_SIZE];
                                    ^
/tmp/OCL16106T7.cl:304:24: error: variables in function scope cannot be declared static
  __local static mix_t mix[GROUP_SIZE];
                       ^
2 errors generated.

error: Clang front-end compilation failed!
Frontend phase failed compilation.
Error: Compiling CL to IR

[OPENCL]:clEnqueueWriteBuffer(-38)

**Comment by cdalvaro2** [comment]
I'm really excited about this pull request!

**Comment by chfast** [comment]
This is going to be replaced by #294. Please test it.

**Comment by chfast** [comment]
Obsoleted by #294. Use `ethminer --cl-parallel-hash 2`

**Pull request closed without merging**
