### PR TITLE
Fix (submit refused by nicehash #151)

### PR DESCRIPTION
**Pull request by AndyLavr**
ℹ  09:50:21|stratum  Invalid nonce size.
 ✘  09:50:21|stratum  :-( Not accepted.

### CODE REVIEW

**Comment by AndyLavr** [comment]
Yes, the problem still exists, but on a smaller scale... :(

**Comment by chfast** [comment]
So does it work or not?

**Comment by AndyLavr** [comment]
@chfast It works, but it is not stable, the first 15 minutes is normal, after they begin to refuse ...

**Comment by chfast** [comment]
This was fixed in #178.

**Pull request closed without merging**
