### PR TITLE
Fix (submit refused by nicehash) next part.

### PR DESCRIPTION
**Pull request by AndyLavr**
ℹ  09:50:21|stratum  Invalid nonce size.
  ✘  09:50:21|stratum  :-( Not accepted.

### CODE REVIEW

**Comment by AndyLavr** [comment]
Tested, works well without errors.

**Comment by AndyLavr** [comment]
Tested, works well without errors. :)

**Comment by AndyLavr** [comment]
Tested, works well without errors. :)

**Comment by EoD** [comment]
@AndyLavr You don't need to close all your pull request. Just use ``git rebase`` and then ``git push -f``to the same branch again in order to change your commits (split them, merge them, amend them, etc).

That's a common practice.

**Pull request closed without merging**
