### PR TITLE
Store AMD binary kernels in compressed archive

### PR DESCRIPTION
**Pull request by jean-m-cyr**
- About 320KB of AMD binaries stored in 9KB compressed tarball
- Binary kernel loader enhanced to extract binaries from archive

### CODE REVIEW

**Comment by chfast** [comment]
How are binary kernels currently distributed?

**Comment by ddobreff** [comment]
In plain format *.bin in subfolder kernels.
The PR has been tested by me a week ago and it works but the question is...is it needed to archive kernels?

**Comment by chfast** [comment]
So they are not distributed with the binary releases of ethminer?

**Comment by ddobreff** [comment]
They are distributed with both source and binary format, but the binary compilation is done before, not in process of user compilation. This is simple enhancement, not actual benefit which I do not mind at all, it saves adding bunch of precompiled kernels into subfolder kernels, nothing more.

**Comment by chfast** [comment]
I'm not sure it is worth to add additional dependencies to have it. Especially when this is only for people building from source (you have to download kernels).

CMake has tar/zip support. Can't we just use it if needed?

**Comment by AndreaLanfranchi** [comment]
Binary releases always have the archive tar or zipped.
I believe such modification would make problems like this (https://github.com/ethereum-mining/ethminer/issues/1773#issuecomment-450030285) a little harder to deal with.

(A simple binary file rename apparently have solved the issue).

**Comment by chfast** [comment]
> Binary releases always have the archive tar or zipped.
> I believe such modification would make problems like this ([#1773 (comment)](https://github.com/ethereum-mining/ethminer/issues/1773#issuecomment-450030285)) a little harder to deal with.
> 
> (A simple binary file rename apparently have solved the issue).

I agree here. Debugging issues with binary kernels seems to be easier when you have them unpacked.

Some of my previous comments are not accurate because I thought binary kernels are not included in the releases.

**Comment by ddobreff** [comment]
Closing for now

**Pull request closed without merging**
