### PR TITLE
Faster console update of hashrate (backport for v.0.16)

### PR DESCRIPTION
**Pull request by StefanOberhumer**
This is a minimal update to get faster actual hashrate - only for 0.16.
Master fix was done with commit c343cefa14dcb6f9547bbb86a05fab485a72b4a3 .

### CODE REVIEW

**Comment by StefanOberhumer** [comment]
@chfast, @XhmikosR 
Ouhhh - the hasrate is now flickering ....
**DONT MERGE**
Have to check more !

**Comment by XhmikosR** [comment]
Yeah, also this isn't a cherry-pick, it's a new patch.

**Comment by StefanOberhumer** [comment]
Or better a backport...

**Comment by XhmikosR** [comment]
Do we close this now?

**Comment by StefanOberhumer** [comment]
Yes, we close it.

**Pull request closed without merging**
