### PR TITLE
CUDA: Allow enum devices ordered by PCI information

### PR DESCRIPTION
**Pull request by StefanOberhumer**
etheminer and nvidia-smi uses different ids for GPU indexing.
It seems nvidia-smi enumerates the devices based on the PCI address.

When using "--cuda-devices-enum pci" the displayed gpu id in
ethminer matches those used in nvidia-smi.
So its easier to adjust settings (overclock/power) using nvidia-smi
with the same id reported in ethminer.

### CODE REVIEW

**Comment by jean-m-cyr** [comment]
I understand your desire to cleanup things like trailing spaces and tabs. I often wish I could run the whole thing through astyle. But it makes diffs hard to read, and hinders inspection.

I not sure if there's an established TAB policy for this projects, but there are two schools of thought on TAB use.

pro tab: reduces file size and facilitates editing with some editors.

anti tab: not everyone uses the same editor tab settings. Spaces always look the same.

It really gets ugly if there's a mix of tabs and spaces.

As for your functional change, why did you make it optional via command line parameter. Why wouldn't you make this numbering scheme the standard?

**Comment by StefanOberhumer** [comment]
1. Trailing  whitespaces
My checkin-scripts warn me about trailing spaces.
So I made an extra commit for just removing the trailing spaces as they are usually only noise.

2. Use tabs for indentation
I you look at the code you'll see someone has used spaces for indent  with a tab size of 8 for only some less codelines while the rest of the code uses tab for indentation. So I corrected ~30 lines of code so that the indent is in the same format as the rest of the code.
I personally do not use tabs for indent (always use spaces because it looks always the same way).
But if I use it I usually have a tab size of 4 - so I recognize the existing difference !

3. Functional change - not default ?
Maybe some users already uses "--cuda-devices" option or scripts parsing the result of request by the "--api-port" interface.
I don't wanted to force them to update all their scrips and logic as the enumeration of the cards changes within etherminer.

**Comment by chfast** [comment]
For code formatting: I will introduce clang-format config soon, taken from cpp-ethereum.

To ignore whitespace add `?w=1` to the URL: https://github.com/ethereum-mining/ethminer/pull/492/files?w=1.

**Comment by StefanOberhumer** [comment]
I don't wanted to start a source code formatting discussion ;-) ;-)
I just saw trailing (noisy) whitespaces and about 30 lines of code in the files I had to edit  that were not indent like the rest of the code.
So I just "corrected" those things.

**Comment by chfast** [comment]
@StefanOberhumer it's not because of you. I recently added clang-format support to cpp-ethereum. I'd like all C++ Ethereum-related projects to share the same code layout.

**Comment by EoD** [comment]
@StefanOberhumer Can you just drop (via git-rebase) your commits which format code you did not touch? As far as I understand chfast will format the whole codebase as soon as #503 has been merged.

**Comment by chfast** [comment]
I will not.

**Comment by EoD** [comment]
Well, then just wait with the formatting until we have the clang-format config finished.

**Comment by StefanOberhumer** [comment]
I'll adapt my pull request and add just the functional changes...

**Pull request closed without merging**
