### PR TITLE
CUDA: Drop Compute 2.0 architecture

### PR DESCRIPTION
**Pull request by chfast**

### CODE REVIEW

**Comment by chfast** [comment]
@davilizh, can you check it out?

**Comment by davilizh** [comment]
I do not know whether people will use Tesla and Quadro GPUs for mining, if they use, then we miss: "P100	6.0" and "Quadro GP100	6.0"

**Comment by chfast** [comment]
You mean P100 and GP100 are Compute 2.0?

**Comment by davilizh** [comment]
No, they are compute 6.0. But we do not have that 6.0 in the cmake file.

**Comment by chfast** [comment]
6.0 added. I'm guessing in case of chips like P100, they were using 5.2.

**Comment by davilizh** [comment]
I also checked sm_3.5, it seems that some device with sm_3.5 has about 4 GB DRAM, so can still mine ethererun.
As a result, the current compute capabilities in our CMAKE file are fine to me.
Thanks :+1:

**Comment by LeChocolateMan** [comment]
Just out of curiosity - would this mean the >6.0 cards can be more stable at higher clocks? or same stability ?

**Pull request merged**
