### PR TITLE
Fix spelling error and add proxy example

### PR DESCRIPTION
**Pull request by jefferson-1**
Fix spelling error (exsamples?? really?)

Add Stratum example 

Edit: Gah Stratum -> Proxy

### CODE REVIEW

**Comment by jean-m-cyr** [comment]
Doesn't belong there! 'proxy' is not a pool!

**Comment by jefferson-1** [comment]
Then where should we post examples? The list literally is an example of how to format the -P parameter and there are NO examples of how to set a proxy to a Pool. For example, if you have 10 PC's on the inside of a network, a Proxy simply performs better than having 10 connections to the same pool.

**Comment by jean-m-cyr** [comment]
I'd suggest changing the 'Servers' header to 'Stratum Servers'. Then add a separate 'Proxy Server' header at the end.

**Comment by jefferson-1** [comment]
Maybe the main readme would be better then. I'll close this request.

**Pull request closed without merging**
