### PR TITLE
Added eth adress for Andrea Lanfranchi

### PR DESCRIPTION
**Pull request by AndreaLanfranchi**

### CODE REVIEW

**Comment by chfast** [comment]
Please use addresses with checksum in public.

**Comment by AndreaLanfranchi** [comment]
@chfast not sure what you mean

**Comment by XhmikosR** [comment]
Is there an online tool that does the conversion?

**Comment by chfast** [comment]
https://etherscan.io/address/0xA7e593Bde6B5900262cf94e4D75Fb040f7fF4727

**Pull request merged**
