### PR TITLE
Add clang-format config

### PR DESCRIPTION
**Pull request by chfast**
Install clang-format 5+.
Use git-clang-format to reformat changed lines.

### CODE REVIEW

**Comment by smurfy** [comment]
As mentioned in gitter the idea is to use clang-format due to other ethereum projects use the same

**Comment by chfast** [comment]
Sorry, in cpp-ethereum I had to pick up something that is at least similar. I'm open for tweaks, but the basic style should stay.

**Comment by EoD** [comment]
@smurfy of course, clang-format is great. I am just wondering if we really need 92 lines of custom configurations and not using ``BasedOnStyle`` with a couple of custom configurations.

**Comment by chfast** [comment]
As you can guess, this config was generated by `clang-format -style=Chromium -dump-config`. That's the reason all options are explicit. This allow you easy tune it, because you see all options available.
Yes, it can be shorted, but I believe in this period when we are experimenting with it, this form is better.

**Comment by jean-m-cyr** [comment]
At what stage is the formatting applied? And to what?

Does it handle .cu files with CUDA extensions.

I'll need to look into clang-format... been using astyle for years.

**Comment by chfast** [comment]
It is much better than astyle, because it is (usually) one way to format a code.

We should require new code changes to be formatted accordingly. git-clang-format is a nice script that integrates with git and can format only git diff (also can format previous commits).

Sometimes, when a bigger part of a file is re-formatted, you can also format whole file, but preferably in a separated commit.

**Comment by jean-m-cyr** [comment]
Any thought of biting the bullet and giving the entire source tree a format pass. Maybe right after a final release?

**Comment by chfast** [comment]
This usually cause a lot of conflicts to functional changes.

**Comment by chfast** [comment]
I'm going to merge this. Simplifications to the config are welcome as following PRs.

**Comment by EoD** [comment]
I will go ahead and simplify it then asap in a follow up PR.

**Comment by EoD** [comment]
@chfast I am struggling to re-create your clang-format file. Which version of clang-format did you use? It seems that you used a mixture of 
* Clang4: ``AlignEscapedNewlinesLeft`` is [only in v4](https://reviews.llvm.org/D32733?vs=97397&id=97404)
* Clang5: ``SplitEmptyFunction`` is only in v5+

I can re-create the current options by using clang5, but this will change a couple of lines:

```patch
--- .clang-format	2018-01-30 11:21:06.373937796
+++ clang-format-v5-dump 13:50:32.292863967
@@ -2,3 +2,2 @@
 Language:        Cpp
-# BasedOnStyle:  Chromium
 AccessModifierOffset: -4
@@ -7,3 +6,3 @@
 AlignConsecutiveDeclarations: false
-AlignEscapedNewlinesLeft: true
+AlignEscapedNewlines: Left
 AlignOperands:   true
@@ -16,2 +15,3 @@
 AllowShortLoopsOnASingleLine: false
+AlwaysBreakAfterDefinitionReturnType: None
 AlwaysBreakAfterReturnType: None
@@ -21,5 +21,3 @@
 BinPackParameters: true
-BreakBeforeBinaryOperators: None
-BreakBeforeBraces: Custom
-BraceWrapping:
+BraceWrapping:   
   AfterClass:      true
@@ -36,6 +34,15 @@
   SplitEmptyFunction: false
+  SplitEmptyRecord: true
+  SplitEmptyNamespace: true
+BreakBeforeBinaryOperators: None
+BreakBeforeBraces: Custom
+BreakBeforeInheritanceComma: false
 BreakBeforeTernaryOperators: false
+BreakConstructorInitializersBeforeComma: false
 BreakConstructorInitializers: BeforeColon
+BreakAfterJavaFieldAnnotations: false
+BreakStringLiterals: true
 ColumnLimit:     100
 CommentPragmas:  '^ IWYU pragma:'
+CompactNamespaces: false
 ConstructorInitializerAllOnOneLineOrOnePerLine: true
@@ -47,4 +54,8 @@
 ExperimentalAutoDetectBinPacking: false
-ForEachMacros:   [ foreach, Q_FOREACH, BOOST_FOREACH ]
-IncludeCategories:
+FixNamespaceComments: true
+ForEachMacros:   
+  - foreach
+  - Q_FOREACH
+  - BOOST_FOREACH
+IncludeCategories: 
   - Regex:           '^".*'
@@ -59,2 +70,3 @@
     Priority:        4
+IncludeIsMainRegex: '(Test)?$'
 IndentCaseLabels: false
@@ -62,2 +74,4 @@
 IndentWrappedFunctionNames: false
+JavaScriptQuotes: Leave
+JavaScriptWrapImports: true
 KeepEmptyLinesAtTheStartOfBlocks: false
@@ -80,3 +94,5 @@
 SortIncludes:    true
+SortUsingDeclarations: true
 SpaceAfterCStyleCast: false
+SpaceAfterTemplateKeyword: true
 SpaceBeforeAssignmentOperators: true
```

**Comment by chfast** [comment]
You can use clang5.

**Pull request merged**
