### PR TITLE
For test purpose, I have modified the code, and want to get the windows exe, will close it later.

### PR DESCRIPTION
**Pull request by davilizh**
It takes me 2 days to build this code for windows, but still failed.
For test purpose, I have modified the code, and want to get the windows exe. I will close it later.
Sorry for bringing you guys in-convenience.

### CODE REVIEW

**Comment by jimmykl** [comment]
Can one of the core devs advise how we can compile on Windows? I have tried Visual Studio 2015, 2017 and various changes to cmake switches but no success either.

**Comment by davilizh** [comment]
@jimmykl I can always build success with linux, but never windows.

**Comment by davilizh** [comment]
Test done, will close the pull request.
Hope the administrator wouldn't blame me

**Comment by davilizh** [comment]
For debug purpose again, please do not care.

**Pull request closed without merging**
