### PR TITLE
Set current epoch context into newly created miner threads.

### LINKED ISSUE #1722: [master] stratum: invalid epoch, dag memory size
**Describe the bug**
invalid epoch, dag memory size for stratum cases. Please see screenshot.

*getWork works with no problem.*

branch point commit 07ea6f91be5135f0678a0aef775c05fa48a286aa
Merge: 4df6898 1ec2342
~~~
Author: Andrea Lanfranchi <andrea.lanfranchi@isiweb.it>
Date:   Wed Nov 28 13:03:12 2018 +0100

    Merge pull request #1721 from ethereum-mining/clang-tidy

    Tune clang-tidy config and fix some warnings**
~~~
**Screenshots (Optional)**
image

### PR DESCRIPTION
**Pull request by StefanOberhumer**
Should fix #1722

### CODE REVIEW

**Comment by StefanOberhumer** [comment]
Farm::setWork() - In case of #1722 the m_miners array is empty. (The miners get created later - so 
```
 for (unsigned int i = 0; i < m_miners.size(); i++)
        {
            m_miners.at(i)->setEpoch(m_currentEc);
        }
``` does not work!

**Comment by StefanOberhumer** [comment]
Add a `cnote << "Farm::setWork() - m_miners.size() " << m_miners.size();` as first line to Farm::setWork() and try using 
```-P stratum+tcp://\\`aminer.pooltester\\`:x@asia.ethash-hub.miningpoolhub.com:20535```  (sample comes from https://github.com/ethereum-mining/ethminer/blob/master/scripts/testpools.bash )

**Comment by AndreaLanfranchi** [comment]
I see but the problem is completely different and your patch works around but does not correct.

A proper flow should out this
```
cnote << "Established connection to " << m_selectedHost;
```

called from PoolManager but in example #1722 there is not.

This means we miss a call to m_onConnected which is the real problem to be solved.
Patching it quickly

**Comment by StefanOberhumer** [comment]
Outdated due #1728

**Pull request closed without merging**
