### PR TITLE
New API methods

### PR DESCRIPTION
**Pull request by AndreaLanfranchi**
* miner_getconnections
* miner_setactiveconnection
* miner_addconnection
* miner_removeconnection

### CODE REVIEW

**Comment by AndreaLanfranchi** [comment]
These new implementation _may_ improve control and handling of large mining operations.

**Comment by ddobreff** [comment]
Looks good but probably fallback connection and priority set also can be considered.

**Comment by AndreaLanfranchi** [comment]
@ddobreff can you elaborate ? Not sure if I get you.

**Comment by AndreaLanfranchi** [comment]
I see your point.
But question is if API interface should honor same behavior of CLI arguments (where, atm, you can't do anything else than prioritize pools by the order of insertion) or if it should implement something new.

**Comment by ddobreff** [comment]
Well, failover and primary is already implemented in CLI, so API shoud follow same idea, those are my 2 cents :)

**Comment by AndreaLanfranchi** [comment]
In CLI the concept is slightly different.

Suppose you enter these pools  as one two three

```
-P stratum+tcp://<whatever>@eu1.ethermine.org:4444
-P stratum+tcp://<whatever>@eu1.ethermine.org:14444
-P stratum+tcp://<whatever>@eth-eu1.nanopool.org:9999

```

If you do not set any value for the CLI argument `--failover-timeout` there is no concept of "primary" pool. All those three are peers and ethminer will connect first to first pool, then, for wichever reason it may fail, will switch to second. If this one will fail too will switch to third. If third will fail too eventually will return to first ... in a never ending loop.

On the other hand if you set --failover-timeout to whichever value the concept changes to

```
-P stratum+tcp://<whatever>@eu1.ethermine.org:4444		PRIMARY
-P stratum+tcp://<whatever>@eu1.ethermine.org:14444		FAILOVER   (peer)
-P stratum+tcp://<whatever>@eth-eu1.nanopool.org:9999	        FAILOVER   (peer)

```
Under this circumnstance there is no change about ethminer's behavior **for first pool** but it will behave differently when, if switched to pool number 2 (for whichever reason), it will stay there until `--failover-timeout` elapses and then it will try to reconnect to pool number 1

Actually API methods integrate with this logic.

**Pull request merged**
