### PR TITLE
Support Zilliqa mining 

### PR DESCRIPTION
**Pull request by deepgully**
This PR aims to support Zilliqa getWork APIs. https://github.com/Zilliqa/Zilliqa

Zilliqa introduced a new PoW design, every node need to run PoW to join the network. but can not get rewards directly from the PoW.
The miners will only need to run PoW for ~2 mins of every DS epoch(~1.2 hrs on current testnetv3).

The major changes are:
1) fix bugs for getWork protocol, add a new scheme "zil".
2) changes for Zilliqa's specific PoW design.

### CODE REVIEW

**Comment by smurfy** [comment]
My remarks:

* ``isZILMode``  should not be part of PoolClient, its similiar to the different stratum protocols so it should be only in getwork client
* rename ``GetworkVersion`` to ``GetworkProtocol`` (again similiar to stratum https://github.com/ethereum-mining/ethminer/blob/master/libpoolprotocols/stratum/EthStratumClient.h#L54)
* i really dont like using farm in the client at all. You already send a pause m_onWorkReceived work package. so somehow use that?
* I like configurable reconnect delay 👍 
* Not sure if i like the max submit logic. maybe move it to Client not within the miner? Not sure.

@AndreaLanfranchi  has done a lot of awesome refactoring of the stratum client so he probably can give a lot more/better feedback than i

**Comment by smurfy** [comment]
Regarding the pause thing. we have something similiar in stratum: https://github.com/ethereum-mining/ethminer/blob/master/libpoolprotocols/stratum/EthStratumClient.cpp#L461

but this would cause pool manager to reconnect and possible switch pools.  So maybe a new callback/event ``m_onNoWorkReceived`` and pool manager pauses? And it probably auto-resumes already if ``m_onWorkReceived`` is called.

**Comment by ddobreff** [comment]
Instead of just pause, relay mechanism can be used, because ZIL only sends work when performing PoW. During other period it can just use stop/start + fallback to constant ethash mining pool. Ex: ethminer -P zil://... -P stratum+tcp://... where zil is prefered mining pool and stops once PoW is done and starts when start msg is being received.

**Comment by ddobreff** [comment]
Guys keep in mind this is very important PR, due to Zilliqa not being standard PoW currency.
So far their community wasn't able to provide dedicated miner and you had to use the node to mine. I fully support that integration.

**Comment by chfast** [comment]
Me too (for other reasons).
But some time ago I allowed "big and very important" PRs and that was mistake.

Besides, this is being reviewed. So let's move one.

**Comment by chfast** [comment]
If this is important, I can make a side release of this.

**Comment by AndreaLanfranchi** [comment]
My two cents.

- addition of a new scheme is not needed : the protocol is still getWork and the comunications among work provider and work consumer stay the same. What changes (as far as I understand) is the behavior ethminer should implement on no work from work provider. To change that behavior better use a new CLI argument as `algo` or feed additional parameters using the query part of the URI definition to work provider.
- introduction of `delayBeforeRetry` is arguable. Users struggle to have the less interval possible to switch to failover connections. If needed - at least - set its value to zero
- All logic about pausing/restarting Farm due to lack of work (due to node not running PoW) should be moved into PoolManager.
- Too many checks over new work package being different from previous work package
- This change https://github.com/ethereum-mining/ethminer/pull/1813/files#diff-e500f3f717b3e0d46f351d9d546cfd33R156 makes no sense as POST requests are never cached neither by intermediate proxies. It only adds unnecessary bytes headers to transfer
- I don't endorse this change also https://github.com/ethereum-mining/ethminer/pull/1813/files#diff-e500f3f717b3e0d46f351d9d546cfd33R205. Let the socket return whenever the socket buffer is ready instead of waiting for eof.

**Comment by AndreaLanfranchi** [comment]
A personal consideration ... is it worth to keep miner idle for a considerable amount of time ?
If node is not supposed to send work for some time wouldn't it be better to switch to another pool and do some work ?

Also I totally do not understand the need of implementation m_maxSubmit for **all** modes.
Ethminer is designed to send all the solutions it finds (in fixed diff pools any solution after the firs might be compliant with higher difficulty).

**Comment by ddobreff** [comment]
Its not standard getwork protocol and since it doesn't run constantly it is better to use switch case in order to continue mining something else until DS epoch message arrives.

**Comment by AndreaLanfranchi** [comment]
Another thing. If wait time on getwork client exceeds no-work-timeout poolmanager disconnects.
So the two must be handled in sync.

**Comment by AndreaLanfranchi** [comment]
Sorry trivial question but I'm not that much into zilliqa ... how about DAG and epochs ? 

Are they the same as ethash ?

**Comment by ddobreff** [comment]
It follows same path as ethash but I am not quite sure about how DAG epochs are calculated on their implementation.

**Comment by AndreaLanfranchi** [comment]
> It follows same path as ethash but I am not quite sure about how DAG epochs are calculated on their implementation.

I think it's fundamental ... actually our epochs are computed on behalf of @chfast 's ethash library (when only seed available) or on constant divisor of 30k blocks when work provider pushes it.
Yet to be settled if same epoch number produces same DAG size.

**Comment by ddobreff** [comment]
Its not even standard getwork, the PR maker github account contains zilpool project though...

**Comment by AndreaLanfranchi** [comment]
> Its not even standard getwork,

Well ... actually the message exchange protocol is the same. It adds extra array elements in the payload of response which dictates how much time to next retry. Due to this we need to adapt ethminer behavior accordingly.

**Comment by smurfy** [comment]
The actual protocol is ``JSONRPC``:D but similiar to the existing getwork "protocol" used in geth/parity. So a variant similiar to stratum variants.

Also the no work timeout is enforced by the client not the manager so it would be no problem. If handled correctly.

Since @AndreaLanfranchi dislikes most of the same things as i, i'm happy to refactor this. 

Also since the similarity with getwork (just additional entries) i guess we even can do some autodetection. But i still would do the zilla protocol thingy or (getwork1/2) similiar to stratum.

**Comment by AndreaLanfranchi** [comment]
I dislike various things of this PR. Not saying it's not worth implementing a zilliqa compatible behavior.
I believe that this can be integrated with very few lines of code in the progpow-enabled ethminer version I am working on.

**Comment by ddobreff** [comment]
By me, its totally worth it. I have been monitoring this project for over a year, its not some scammy fork of ethash.

**Comment by AndreaLanfranchi** [comment]
> Also the no work timeout is enforced by the client not the manager so it would be no problem. If handled correctly.

Sorry ... yes you are correct.

**Comment by ShengguangXiao** [comment]
@AndreaLanfranchi @deepgully I setuped a mining pool http://35.165.179.13:4202/api. And a small testnet connected to this pool to request pow, the small testnet explorer is https://proxy3-explorer.aws.z7a.xyz

**Comment by deepgully** [comment]
> @AndreaLanfranchi @deepgully I setuped a mining pool http://35.165.179.13:4202/api. And a small testnet connected to this pool to request pow, the small testnet explorer is https://proxy3-explorer.aws.z7a.xyz

connect the pool
```bash
./ethminer -v 1 --report-hr=1 --max-submit=1 --farm-recheck 5000 --work-timeout 7200 --farm-retries 10 --retry-delay 30 \
    -P zil://0x0123456789012345678901234567890123456789.worker_name@35.165.179.13:4202/api
```

**Comment by deepgully** [comment]
Thx for your comments, I will separate this PR to 1) fixes 2) ZIL specific changes.

**Comment by deepgully** [comment]
@AndreaLanfranchi , thx for your comments, reply with my thoughts FYI.

> * introduction of `delayBeforeRetry` is arguable. Users struggle to have the less interval possible to switch to failover connections. If needed - at least - set its value to zero

the pool needs to re-start sometimes, I add this delay to ensure ethminer can re-connect to pool automatically instead of terminated itself in quick.

> A personal consideration ... is it worth to keep miner idle for a considerable amount of time ?
If node is not supposed to send work for some time wouldn't it be better to switch to another pool and do some work ?
> * All logic about pausing/restarting Farm due to lack of work (due to node not running PoW) should be moved into PoolManager.

The DAG# are diff between ZIL and ETH, so currently we didn't support dual-mining in one ethminer, fallback mechanism could be useful for dual-mining, but the question is how to awake ZIL client when next PoW window is coming.  Also, during one ZIL PoW window, the client will not get new work constantly, I don't want the Farm switch between ZIL/ETH too frequently,

PoolManager needs more information to control the clients, current PoolManger::rotateConnect can not handle it.

I need further study to implement dual-mining for ZIL and Others.

> * Too many checks over new work package being different from previous work package

I added this because a ZIL Node will do 2 works in one PoW window, with same header and different boundary. one is for Shard(lower difficultly), another one is for DS( much higher difficultly).

> * This change https://github.com/ethereum-mining/ethminer/pull/1813/files#diff-e500f3f717b3e0d46f351d9d546cfd33R156 makes no sense as POST requests are never cached neither by intermediate proxies. It only adds unnecessary bytes headers to transfer

sorry for that, this code is for testing purpose and forgot to clean up, will be fixed.

> * I don't endorse this change also https://github.com/ethereum-mining/ethminer/pull/1813/files#diff-e500f3f717b3e0d46f351d9d546cfd33R205. Let the socket return whenever the socket buffer is ready instead of waiting for eof.

the getWork wont work if ethminer got partial response from socket.
Also, getWork is HTTP request without keep-alive, so I think read to eof is suitable here.

> Also I totally do not understand the need of implementation m_maxSubmit for all modes.
Ethminer is designed to send all the solutions it finds (in fixed diff pools any solution after the first might be compliant with higher difficulty).

we add m_maxSubmit because current the difficulty is very low, too many submits to Node cause problem, I think the value can be set to -1(submit all) by default.

**Comment by deepgully** [comment]
> Sorry trivial question but I'm not that much into zilliqa ... how about DAG and epochs ?
> 
> Are they the same as ethash ?

the algo is same but the block number is different. ZIL using DS block number for PoW, that block number will increased very slow (~1 hr by current testnetv3).

**Comment by deepgully** [comment]
> Another thing. Is Pool mining by stratum ever implemented on zilliqa ?
> I mean ... is only getWork ?

only getWork right now.

**Comment by deepgully** [comment]
> @deepgully can you point me to a connection to a zilliqa node so I can make few tests ?

`150.95.212.222:4202`

a real node in ZIL testnet, but you have waiting for ~1.2 hrs to got 2 works for your GPUs  :)

```
./ethminer -v 1 --report-hr=1 --max-submit=10 --farm-recheck 5000 --work-timeout 7200 --farm-retries 10 --retry-delay 30 \
    -P zil://0x9876543210012345678998765432100123456789.worker_name@150.95.212.222:4202
```

**Comment by AndreaLanfranchi** [comment]
Another point. You actually put the thread to sleep while waiting for next PoW window.
This might be a problem : actually connection clients do not have their own thread. Making that long sleep might stall the entire application.

Thread scheme for ethminer is this
- 1 thread for each miner (ie for each gpu)
- 1 thread for boost's IO service
- 1 thread for all the rest

**Comment by jean-m-cyr** [comment]
I don't understand the purpose of the --max-submit parameter. When is it better to limit the number of submits per pass? There can be many valid solutions for any given job.

**Comment by ShengguangXiao** [comment]
> I don't understand the purpose of the --max-submit parameter. When is it better to limit the number of submits per pass? There can be many valid solutions for any given job.

For Zilliqa mining, only one solution is enough, others is redundant.

**Comment by deepgully** [comment]
@all, I will close this PR and create new PRs, thx for your support.

**Pull request closed without merging**
