### PR TITLE
Add POOLEXSAMPLES_ETH.md to show how to connect to different pools.

### PR DESCRIPTION
**Pull request by StefanOberhumer**
Adding the new -P switch seems to create a lot of issues.
I think it's a good idea to add some documentation how to connect ethminer to a pool.
(As ETC could be different I named the file POOLSAMPLES_ETH.md )

If Issue #1147 is available, this docu could be validated/generated with travis & co. 

I know the documentation is currently not finished (some TODOs, not fully completed)!
But to complete the information I need some feedback and help.
I also test my settings only on linux machines - maybe there is something different on windows (of course - it shouldn't)

So:
* Feel free to Merge the PR and allow more people to collaborate
* Give me feedback and infos - so I can adapt my PR
* As I'm not a native speaker - please check also grammer and typos.

### CODE REVIEW

**Comment by jean-m-cyr** [comment]
I believe this should actually be part of the front page README.md since we have actively changed a lot with respect to parameters lately!

For the nicehash example, you can use:

ethminer ... -P stratum2+tcp://<BTC wallet address>@daggerhashimoto.usa.nicehash.com:3353

**Comment by StefanOberhumer** [comment]
@jean-m-cyr : Are there any worker names available with nicehhash?

**Comment by chfast** [comment]
Very nice!

I agree this could be a part of README. I also would title it "Examples", not "Samples".

**Comment by AndreaLanfranchi** [comment]
> Are there any worker names available with nicehhash?

Yes you can use this syntax

`-P stratum2+tcp://<bitcoin-address>.<workername>@daggerhashimoto.eu.nicehash.com:3353`

**Comment by StefanOberhumer** [comment]
Based on https://etherscan.io/stat/miner?range=7&blocktype=blocks I think just SparkPool should(must) be added to the listed pools in my PR ...  and the TODOs must be fixed in my PR of course.
Also #1142  should be addressed(fixed) for V15 as it seems f2pool makes 16% of the blocks.

**Comment by AndreaLanfranchi** [comment]
@StefanOberhumer  I just pushed PR #1181 to solve #1142

**Pull request merged**
