### PR TITLE
Strip escape codes for Win versions under 10. Issue #728

### PR DESCRIPTION
**Pull request by jean-m-cyr**

### CODE REVIEW

**Comment by smurfy** [comment]
Please consider adding support for this:
http://no-color.org/

Basically if NO_COLOR env is set, don't use colors. Could work on Windows and UNIX

**Comment by jean-m-cyr** [comment]
@smurfy I like that even better than the version check! I don't run Windows so I can't test the getversion call.

**Comment by jean-m-cyr** [comment]
Now if I can only get clang to accept regex_replace syntax

**Comment by Alex-ASF** [comment]
No need to check the version, it's not good (IMHO). 
Because there are third-party consoles that support ANSI colors. For example, Cygwin supports ANSI.

**Comment by jean-m-cyr** [comment]
@Alex-ASF Latest commit doesn't check Win version. Uses NO_COLOR env. variable.

**Pull request merged**
