### PR TITLE
Added 8 and expanded on 4

### PR DESCRIPTION
**Pull request by gidoBOSSftw5731**
Self Explained (..?)

### CODE REVIEW

**Comment by smurfy** [comment]
Please correct typos

**Comment by chfast** [comment]
@gidoBOSSftw5731 Are you going to fix the typos?

**Comment by gidoBOSSftw5731** [comment]
Oh, my bad, will do in a few hours... Sorry bout that

**Comment by gidoBOSSftw5731** [comment]
Sorry that I was a idiot

**Comment by gidoBOSSftw5731** [comment]
Oh wait, sorry... now i see...

**Comment by amirulali** [comment]
This one too...

No. Your VRAM must be above the DAG size (**CUrrently** about 2.15 GB.)

**Comment by amirulali** [comment]
Should be performance

...  to get best preformance ...

**Comment by gidoBOSSftw5731** [comment]
Eh?

**Pull request merged**
