### PR TITLE
Hardware Monitoring for NVML, ADL and AMDGPU SysFS

### PR DESCRIPTION
**Pull request by smurfy**
This PR adds Hardware Monitoring to ethminer.
It (optionally) displays GPU Temp and Fanspeed percent to console and is available via API.

* Support for NVML (tested on Windows + Linux)
* Support for ADL (tested on Windows, should work on Linux)
* Support for AMDGPU Linux SysFS (tested on Linux)
* Added option ``-HWMON`` to enable cli display
* NOT Supported by osx. If we find the nvml/adl .so on osx it could be possible to support

~~NVML and ADL on linux uses HARDCODED Paths to the .so files.  This works on my archlinux but not on ubuntu. We need some testing what happens if only the .so file without the path is set.~~

### CODE REVIEW

**Comment by Blacksuu** [comment]
-HWMON on windows 7 work fine & nice add !!!
[[img]https://i.imgur.com/FMSU2LW.png[/img]](url)
cheers

**Comment by amirulali** [comment]
Couldn't get it to run on Linux (Ubuntu 16.04.3, Nvidia 384.69, Cuda 8.0.61-1)

$ git clone git@github.com:smurfy/ethminer.git smurfy
$ cd smurfy
$ git checkout hwmon
$ mkdir build; cd build
$ cmake .. -DETHASHCUDA=ON
$ cmake --build .
$ build/ethminer/ethminer -HWMON
Invalid argument: -HWMON
$ grep HWMON ../ethminer/MinerAux.h
		else if ((arg == "-HWMON") && i + 1 < argc)
			<< "    -HWMON Displays gpu temp and fan percent." << endl
$

**Comment by smurfy** [comment]
change output to:

``gpu/0 25.64 53C 78%  gpu/1 25.64 53C 78%``

**Comment by smurfy** [comment]
Well i think this one is ready to be merged

**Comment by chfast** [comment]
@smurfy it would have been nice to get an approval from someone before merging it.

**Comment by smurfy** [comment]
@chfast @ddobreff gave it via gitter, sorry

**Comment by legotheboss** [comment]
Is this temperature data working with the Claymore-compatibility JSON-API?

**Pull request merged**
