### PR TITLE
Make fast exit algorithm optional for AMD

### PR DESCRIPTION
**Pull request by jean-m-cyr**
- Add --cl-noexit parameter to disable fast exit
- Modify opencl ethash to support no exit
- Create noexit versions of binary kernels
- Adjust binary kernel MAX_SEARCH_RESULT to match host code
- Combine binary kernels into single compressed tar file
- support extracting and loadin binary kernels from
  compressed tar file
- Simplify opencl make
- Remove unused methods
- Format logged power appropriately

### CODE REVIEW

**Comment by jean-m-cyr** [comment]
Binary kernel file space shrinks from 320K to 8K...

**Comment by jean-m-cyr** [comment]
This PR does not touch the DAG generation logic!

**Comment by jean-m-cyr** [comment]
Sure, I can break this up into separate PRs.

**Comment by chfast** [comment]
BTW, when you force push to existing PR you can replace / squash commits this way. No need to open new PR.

**Comment by jean-m-cyr** [comment]
Closing to resubmit as multiple separate PRs.

**Pull request closed without merging**
