### PR TITLE
Travis code format check

### PR DESCRIPTION
**Pull request by StefanOberhumer**
Add a small code format check before any compilation starts on travis:
Check in *.cpp and *.h following things:

* UNIX lineendings
* No tab as indent
* No trailing whitespaces

### CODE REVIEW

**Comment by jean-m-cyr** [comment]
I'm not really qualified to comment on this...

**Comment by XhmikosR** [comment]
One thing I'd add is a .gitattributes file to enforce LF.

**Comment by chfast** [comment]
This looks ok, but wouldn't it be easier to run clang-format and in case it produces any output make it the error.

**Comment by StefanOberhumer** [comment]
@chfast 
I encountered, that blocks under `#if 0 / #endif` were ignored by clang format.
Thought before long playing with .clang-format I used my "prior clang-format times" script.

**Comment by StefanOberhumer** [comment]
@XhmikosR  .gitattributes added (forcing LF for *.cpp, *.h, *.py, *.bash, *.sh)

**Comment by StefanOberhumer** [comment]
@AndreaLanfranchi  @chfast @ddobreff @XhmikosR and @EveryoneElseWhoHasAnOpinion
Would like to close this PR so requesting a feedback:
1.) Should I modify this PR matching https://github.com/ethereum/evmc/pull/104/commits/b290ef3dd027c7579a71c280bbe3933495f8ad81
2.) If so - should clang-format run on every build (travis, appveyor, circleci) if clang-format is available?
3.) Should .gitattributes file being added (at current master there is no .gitattributes)?
4.) Or - Should I (unmerged) close this PR?

**Comment by chfast** [comment]
1. Using clang-format strictly as in EVMC is probably too heavy. We can afford it in EVMC, because it is really tiny library. If you want to try, we can enable the test like this but allow it to fail at the beginning.
2. It is enough to run it once. I recommend Circle CI.
3. We should add .gitattributes if they help.
4. If this script helps detecting basic formatting issues I would merge it and maybe later replace it with clang-format.

**Comment by StefanOberhumer** [comment]
@chfast: Added `--warn` to the testscript.
That means: Miss formatted code is just "printed" but the script exits with success. ==> you have to look into "travis-ci log".
(Example: https://travis-ci.org/ethereum-mining/ethminer/jobs/423711204 section before_install.1)

**Comment by XhmikosR** [comment]
I can't comment on this solution itself since personally I'm used to using astyle, but .gitattributes is needed to make sure the files have the line endings we want regardless of the git settings.

**Pull request merged**
