### PR TITLE
Remove duplicate job test... does more harm than good!

### PR DESCRIPTION
**Pull request by jean-m-cyr**
None of these are duplicates!!!

 X 14:17:32 stratum  **Duplicate job #99d1de93… discarded**
 i 14:17:36 stratum  Job: #447e59f9… us1-etc.ethermine.org [54.177.207.188:5555]
 X 14:17:36 stratum  **Duplicate job #447e59f9… discarded**
 i 14:17:41 stratum  Job: #84034167… us1-etc.ethermine.org [54.177.207.188:5555]
 X 14:17:41 stratum  **Duplicate job #84034167… discarded**
 i 14:17:42 cuda-1   Solution: 0xe139927e7a7120fa
 i 14:17:42 stratum  **Accepted  73 ms. us1-etc.ethermine.org [54.177.207.188:5555]
 i 14:17:53 cuda-3   Solution: 0xe139947e8a30fb28
 i 14:17:53 stratum  **Accepted  73 ms. us1-etc.ethermine.org [54.177.207.188:5555]
 i 14:18:11 stratum  Job: #f8e8f361… us1-etc.ethermine.org [54.177.207.188:5555]
 X 14:18:11 stratum  **Duplicate job #f8e8f361… discarded**
 i 14:18:25 cuda-0   Solution: 0xe139917e8cd7d0e4
 i 14:18:26 stratum  **Accepted  73 ms. us1-etc.ethermine.org [54.177.207.188:5555]
 i 14:18:27 stratum  Job: #85308bdd… us1-etc.ethermine.org [54.177.207.188:5555]
 X 14:18:27 stratum  **Duplicate job #85308bdd… discarded**
 i 14:18:29 cuda-0   Solution: 0xe139917e7c721ed9
 i 14:18:29 stratum  **Accepted  74 ms. us1-etc.ethermine.org [54.177.207.188:5555]
 i 14:18:32 cuda-3   Solution: 0xe139947e804d2f62
 i 14:18:32 stratum  **Accepted  74 ms. us1-etc.ethermine.org [54.177.207.188:5555]
 i 14:18:37 stratum  Job: #d402e39b… us1-etc.ethermine.org [54.177.207.188:5555]
 X 14:18:37 stratum  **Duplicate job #d402e39b… discarded**
 i 14:18:44 stratum  Job: #a14b8581… us1-etc.ethermine.org [54.177.207.188:5555]
 X 14:18:44 stratum  **Duplicate job #a14b8581… discarded**
 i 14:18:45 stratum  Job: #4732a304… us1-etc.ethermine.org [54.177.207.188:5555]

### CODE REVIEW

**Comment by jean-m-cyr** [comment]
The only thing I could think of is a possible race condition... lists are not thread safe, and clear() happens under different thread... I think?

**Comment by lesjokolat** [comment]
I just wanted to let you guys know. I have made no changes at all outside of running todays latest build. so 3 pr from yesterday to today difference and i am seeing a 10% bump in speed on mining pool hashrate im on. incredible! thanks

**Comment by jean-m-cyr** [comment]
I can't think of anything that would explain a 10% increase...

**Comment by lesjokolat** [comment]
I have been running for past 24 hrs. Its still running at that bumped up level.. I even had a couple restarts to try and see if it was a fluke... Maybe a setting on the pool im connected to? I am not complaining...

**Pull request merged**
