### PR TITLE
Fix cuda hash mis-count (stabilize hash rate)

### PR DESCRIPTION
**Pull request by jean-m-cyr**
- In cuda with streams greater than one (default = 2) cuda
  would silently drop hash counts for all streams except one
  at each job switch.

  Fix by making sure that all streams are synchronized and
  accounted for, including potential stale solutions, before
  exiting the search loop.

### CODE REVIEW

**Comment by jean-m-cyr** [comment]
@AndreaLanfranchi I think this might explain the lowered HR you mentioned previously?

**Comment by AndreaLanfranchi** [comment]
> I think this might explain the lowered HR you mentioned previously?

Good catch ... this explains not the lowered HR in general but the wider dips during switching of jobs.

**Comment by jean-m-cyr** [comment]
Not sure how the overall HR is calculated for display... I seem to recall 1 second poling intervals with averaging over 10 seconds... Could have change though?

**Comment by AndreaLanfranchi** [comment]
AFAIK is still that way.

**Comment by AndreaLanfranchi** [comment]
Excellent catch

```
Before

  m  19:16:03|ethminer|  Speed 131.24 Mh/s    gpu/0 23.07  gpu/1 23.07  gpu/2 19.52  gpu/3 22.99  gpu/4 19.52  gpu/5 23.07  [A123+2:R0+0:F0] Time: 01:03
  m  19:16:08|ethminer|  Speed 131.40 Mh/s    gpu/0 23.07  gpu/1 23.07  gpu/2 19.60  gpu/3 23.07  gpu/4 19.52  gpu/5 23.07  [A123+2:R0+0:F0] Time: 01:03
  ?  19:16:11|stratum |  New job #a755dbc7…   eu1.ethermine.org [188.165.226.213:4444]
  ?  19:16:12|stratum |  New job #f8f09d59…   eu1.ethermine.org [188.165.226.213:4444]
  m  19:16:13|ethminer|  Speed 130.74 Mh/s    gpu/0 22.90  gpu/1 22.99  gpu/2 19.40  gpu/3 22.99  gpu/4 19.49  gpu/5 22.99  [A123+2:R0+0:F0] Time: 01:03
  m  19:16:18|ethminer|  Speed 130.74 Mh/s    gpu/0 22.99  gpu/1 22.99  gpu/2 19.49  gpu/3 22.90  gpu/4 19.40  gpu/5 22.99  [A123+2:R0+0:F0] Time: 01:03
  ?  19:16:23|cuda-1  |  Nonce 0x8cb7053c54fdf6c3
  ?  19:16:23|stratum |  **Accepted   44ms.   eu1.ethermine.org [188.165.226.213:4444]
  m  19:16:23|ethminer|  Speed 130.74 Mh/s    gpu/0 22.99  gpu/1 22.90  gpu/2 19.49  gpu/3 22.99  gpu/4 19.49  gpu/5 22.90  [A124+2:R0+0:F0] Time: 01:04
  m  19:16:28|ethminer|  Speed 131.97 Mh/s    gpu/0 23.14  gpu/1 23.14  gpu/2 19.70  gpu/3 23.14  gpu/4 19.70  gpu/5 23.14  [A124+2:R0+0:F0] Time: 01:04
  m  19:16:33|ethminer|  Speed 131.82 Mh/s    gpu/0 23.14  gpu/1 23.14  gpu/2 19.62  gpu/3 23.14  gpu/4 19.62  gpu/5 23.14  [A124+2:R0+0:F0] Time: 01:04
  ?  19:16:35|stratum |  New job #1add8e80…   eu1.ethermine.org [188.165.226.213:4444]
  m  19:16:38|ethminer|  Speed 131.40 Mh/s    gpu/0 23.07  gpu/1 23.07  gpu/2 19.60  gpu/3 23.07  gpu/4 19.52  gpu/5 23.07  [A124+2:R0+0:F0] Time: 01:04
  m  19:16:43|ethminer|  Speed 131.49 Mh/s    gpu/0 23.07  gpu/1 23.07  gpu/2 19.60  gpu/3 23.07  gpu/4 19.60  gpu/5 23.07  [A124+2:R0+0:F0] Time: 01:04
  m  19:16:48|ethminer|  Speed 131.32 Mh/s    gpu/0 23.07  gpu/1 23.07  gpu/2 19.52  gpu/3 23.07  gpu/4 19.52  gpu/5 23.07  [A124+2:R0+0:F0] Time: 01:04
  m  19:16:53|ethminer|  Speed 131.82 Mh/s    gpu/0 23.14  gpu/1 23.14  gpu/2 19.62  gpu/3 23.14  gpu/4 19.62  gpu/5 23.14  [A124+2:R0+0:F0] Time: 01:04
  ?  19:16:56|stratum |  New job #f192cd9a…   eu1.ethermine.org [188.165.226.213:4444]
  m  19:16:58|ethminer|  Speed 131.49 Mh/s    gpu/0 23.07  gpu/1 23.07  gpu/2 19.60  gpu/3 23.07  gpu/4 19.60  gpu/5 23.07  [A124+2:R0+0:F0] Time: 01:04
  ?  19:16:59|stratum |  New job #9b4654c5…   eu1.ethermine.org [188.165.226.213:4444]
  ?  19:17:00|stratum |  New job #20324f92…   eu1.ethermine.org [188.165.226.213:4444]
  ?  19:17:02|stratum |  New job #67aa80b6…   eu1.ethermine.org [188.165.226.213:4444]
  m  19:17:03|ethminer|  Speed 129.45 Mh/s    gpu/0 22.76  gpu/1 22.76  gpu/2 19.20  gpu/3 22.76  gpu/4 19.20  gpu/5 22.76  [A124+2:R0+0:F0] Time: 01:04
  ?  19:17:07|cuda-0  |  Nonce 0x8cb7043c4d04bcf1
  ?  19:17:07|stratum |  **Accepted   44ms.   eu1.ethermine.org [188.165.226.213:4444]
  m  19:17:08|ethminer|  Speed 129.96 Mh/s    gpu/0 22.79  gpu/1 22.79  gpu/2 19.36  gpu/3 22.88  gpu/4 19.36  gpu/5 22.79  [A125+2:R0+0:F0] Time: 01:04
  m  19:17:13|ethminer|  Speed 130.95 Mh/s    gpu/0 23.01  gpu/1 23.01  gpu/2 19.50  gpu/3 22.92  gpu/4 19.50  gpu/5 23.01  [A125+2:R0+0:F0] Time: 01:04
  ?  19:17:17|stratum |  New job #7db565ce…   eu1.ethermine.org [188.165.226.213:4444]

After

  m  19:39:31|ethminer|  Speed 131.17 Mh/s    gpu/0 23.07  gpu/1 23.07  gpu/2 19.49  gpu/3 23.07  gpu/4 19.49  gpu/5 22.98  [A6+0:R0+0:F0] Time: 00:03
  m  19:39:36|ethminer|  Speed 131.88 Mh/s    gpu/0 23.15  gpu/1 23.15  gpu/2 19.68  gpu/3 23.15  gpu/4 19.60  gpu/5 23.15  [A6+0:R0+0:F0] Time: 00:03
  m  19:39:41|ethminer|  Speed 131.96 Mh/s    gpu/0 23.15  gpu/1 23.15  gpu/2 19.68  gpu/3 23.15  gpu/4 19.68  gpu/5 23.15  [A6+0:R0+0:F0] Time: 00:03
  m  19:39:46|ethminer|  Speed 131.80 Mh/s    gpu/0 23.15  gpu/1 23.15  gpu/2 19.60  gpu/3 23.15  gpu/4 19.60  gpu/5 23.15  [A6+0:R0+0:F0] Time: 00:03
  ?  19:39:48|stratum |  New job #b04e0b76…   eu1.ethermine.org [51.255.64.43:4444]
  ?  19:39:48|cuda-1  |  Nonce 0x3cdea8265a9f2dce
  ?  19:39:48|stratum |  **Accepted   62ms.   eu1.ethermine.org [51.255.64.43:4444]
  m  19:39:51|ethminer|  Speed 131.78 Mh/s    gpu/0 23.16  gpu/1 23.16  gpu/2 19.58  gpu/3 23.16  gpu/4 19.58  gpu/5 23.16  [A7+0:R0+0:F0] Time: 00:03
  m  19:39:56|ethminer|  Speed 131.78 Mh/s    gpu/0 23.16  gpu/1 23.16  gpu/2 19.58  gpu/3 23.16  gpu/4 19.58  gpu/5 23.16  [A7+0:R0+0:F0] Time: 00:03
  ?  19:40:00|stratum |  New job #a753ee91…   eu1.ethermine.org [51.255.64.43:4444]
  m  19:40:01|ethminer|  Speed 131.35 Mh/s    gpu/0 23.07  gpu/1 23.07  gpu/2 19.58  gpu/3 22.98  gpu/4 19.58  gpu/5 23.07  [A7+0:R0+0:F0] Time: 00:03
  ?  19:40:05|stratum |  New job #44d80b13…   eu1.ethermine.org [51.255.64.43:4444]
  m  19:40:06|ethminer|  Speed 131.19 Mh/s    gpu/0 22.98  gpu/1 22.98  gpu/2 19.64  gpu/3 22.98  gpu/4 19.64  gpu/5 22.98  [A7+0:R0+0:F0] Time: 00:03
  m  19:40:11|ethminer|  Speed 131.00 Mh/s    gpu/0 22.88  gpu/1 22.88  gpu/2 19.64  gpu/3 22.98  gpu/4 19.64  gpu/5 22.98  [A7+0:R0+0:F0] Time: 00:03
  ?  19:40:14|stratum |  New job #5da86375…   eu1.ethermine.org [51.255.64.43:4444]
  m  19:40:16|ethminer|  Speed 131.07 Mh/s    gpu/0 23.00  gpu/1 23.00  gpu/2 19.59  gpu/3 22.90  gpu/4 19.59  gpu/5 23.00  [A7+0:R0+0:F0] Time: 00:03
  ?  19:40:17|stratum |  New job #b2d7b1c6…   eu1.ethermine.org [51.255.64.43:4444]
  m  19:40:21|ethminer|  Speed 131.19 Mh/s    gpu/0 22.98  gpu/1 22.98  gpu/2 19.64  gpu/3 22.98  gpu/4 19.64  gpu/5 22.98  [A7+0:R0+0:F0] Time: 00:04
  ?  19:40:23|cuda-1  |  Nonce 0x3cdea82661cfe67a
  ?  19:40:23|stratum |  **Accepted   44ms.   eu1.ethermine.org [51.255.64.43:4444]
  m  19:40:26|ethminer|  Speed 130.97 Mh/s    gpu/0 22.91  gpu/1 22.91  gpu/2 19.65  gpu/3 22.91  gpu/4 19.65  gpu/5 22.91  [A8+0:R0+0:F0] Time: 00:04
  ?  19:40:28|stratum |  New job #d7b8179e…   eu1.ethermine.org [51.255.64.43:4444]
  m  19:40:31|ethminer|  Speed 131.69 Mh/s    gpu/0 23.16  gpu/1 23.16  gpu/2 19.58  gpu/3 23.07  gpu/4 19.58  gpu/5 23.16  [A8+0:R0+0:F0] Time: 00:04
  ?  19:40:34|stratum |  New job #7a8c78b2…   eu1.ethermine.org [51.255.64.43:4444]
  ?  19:40:35|stratum |  New job #cbb7e8d5…   eu1.ethermine.org [51.255.64.43:4444]
  m  19:40:36|ethminer|  Speed 131.11 Mh/s    gpu/0 23.08  gpu/1 23.08  gpu/2 19.40  gpu/3 23.08  gpu/4 19.40  gpu/5 23.08  [A8+0:R0+0:F0] Time: 00:04
  m  19:40:41|ethminer|  Speed 130.91 Mh/s    gpu/0 22.98  gpu/1 22.98  gpu/2 19.45  gpu/3 23.07  gpu/4 19.45  gpu/5 22.98  [A8+0:R0+0:F0] Time: 00:04
  m  19:40:46|ethminer|  Speed 131.31 Mh/s    gpu/0 23.10  gpu/1 23.10  gpu/2 19.45  gpu/3 23.01  gpu/4 19.55  gpu/5 23.10  [A8+0:R0+0:F0] Time: 00:04
  ?  19:40:48|stratum |  New job #a5772199…   eu1.ethermine.org [51.255.64.43:4444]
  m  19:40:51|ethminer|  Speed 131.77 Mh/s    gpu/0 23.16  gpu/1 23.16  gpu/2 19.57  gpu/3 23.16  gpu/4 19.57  gpu/5 23.16  [A8+0:R0+0:F0] Time: 00:04
  ?  19:40:53|stratum |  New job #6f5bad14…   eu1.ethermine.org [51.255.64.43:4444]
  m  19:40:56|ethminer|  Speed 130.99 Mh/s    gpu/0 22.98  gpu/1 23.07  gpu/2 19.45  gpu/3 23.07  gpu/4 19.45  gpu/5 22.98  [A8+0:R0+0:F0] Time: 00:04
  ?  19:40:58|stratum |  New job #f1f354f1…   eu1.ethermine.org [51.255.64.43:4444]
  m  19:41:01|ethminer|  Speed 131.29 Mh/s    gpu/0 22.98  gpu/1 23.17  gpu/2 19.55  gpu/3 22.98  gpu/4 19.55  gpu/5 23.07  [A8+0:R0+0:F0] Time: 00:04
  
```

**Comment by jean-m-cyr** [comment]
HR is less affected by job arrivals... I think?

**Comment by AndreaLanfranchi** [comment]
Before I had 131.77 as max and 129.5 as lower dip.
After same max and lower dip 130.99.

Sensible.

**Pull request merged**
