### PR TITLE
Display per GPU and total power consumption

### PR DESCRIPTION
**Pull request by jean-m-cyr**
I don't know if it is possible to retrieve power
consumption for Radeon, and I have none to test
with.

### CODE REVIEW

**Comment by ddobreff** [comment]
amdgpu power is exposed in debugfs, not sysfs.

**Comment by smurfy** [comment]
```
int wrap_amdsysfs_get_power_usage(wrap_amdsysfs_handle *sysfsh, int index, unsigned int *milliwatts)
{
	int gpuindex = sysfsh->card_sysfs_device_id[index];
	if (gpuindex < 0 || index >= sysfsh->sysfs_gpucount)
		return -1;

	char dbuf[120];
	snprintf(dbuf, 120, "/sys/kernel/debug/dri/%u/amdgpu_pm_info", gpuindex);

	std::ifstream ifs(dbuf, std::ios::binary);
	std::string line;

	while (std::getline(ifs, line))
	{
		std::smatch sm;
		std::regex regex(R"(([\d|\.]+) W \(average GPU\))");
		if (std::regex_search(line, sm, regex)) {
			if (sm.size() == 2) {
				double watt = atof(sm.str(1).c_str());
				*milliwatts = (unsigned int)(watt * 1000);
				return 0;
			}
		}
		
	}

	return -1;
}
```

**Comment by smurfy** [comment]
For ADL i do not have any code yet.
Also why did you comment out the local switch stuff in CLMiner, its not really related to HWMON changes.

**Comment by jean-m-cyr** [comment]
I'm not really sure we want or need this.  I just thew it together for for personal use, and I have a tendency to dislike clutter so I'd removed so noise as well. It snuck in with the commit.

The status line is getting rather long and this may not be acceptable to many.

**Comment by jean-m-cyr** [comment]
At first glance, with limited knowledge, I don't think it is possible to retrieve the current power consumption directly from a Radeon card or driver. That being the case, I'd drop this change since it can't achieve a consistent view for all card types.

Opinions?

**Comment by smurfy** [comment]
@jean-m-cyr i think this PR is not really needed, thats why i did not include it in the first implementation of HWMON.

I posted the code for amdsysfs (linux) earlier. Should be possible with adl too i think, but not tested yet. (no amd card in my dev windoze machine anymore, so no adl to test on)

**Comment by jean-m-cyr** [comment]
I think we agree that this is not needed. If we all concur then I'll close this.

**Pull request closed without merging**
