### PR TITLE
Remove dbus support.

### PR DESCRIPTION
**Pull request by StefanOberhumer**
See https://github.com/ethereum-mining/ethminer/pull/1619

### CODE REVIEW

**Comment by jean-m-cyr** [comment]
Don't do this. Just recently fixed DBUS build. Some actually use this option.

**Comment by jean-m-cyr** [comment]
DBUS is Linux standard... API is custom/proprietary.

**Comment by StefanOberhumer** [comment]
Have you tried to compile latest master? DBUS does not work (again)!
We also change the output from time to time so the DBUS clients have to adapt their parser each time.
If there would be such a big usage of DBUS I thought there would be more issues about DBUS.

But: Lets keep it in the source (currently not able to compile) and see whats happens!

**Comment by jean-m-cyr** [comment]
Usually when DBUS is broken in a release, we get a problem ticket. I'm not sure exactly what it's used for???

**Comment by StefanOberhumer** [comment]
@jean-m-cyr :  Pls inform me if you encounter an issue about DBUS

**Pull request closed without merging**
