### PR TITLE
A simple JSON API format for supporting Power Usage

### PR DESCRIPTION
**Pull request by Davesmacer**
Hello,

I worked on the API method for getting the power usage, I created my output format as simple as I could:

{
    "ethhashrate":"336745.9h/s",
    "ethhashrates":["20692.1h/s","21007.2h/s","21007.2h/s","21007.2h/s","21112.3h/s","21322.3h/s","21427.4h/s","21217.3h/s","21217.3h/s","20482.1h/s","21322.3h/s","21112.3h/s","21112.3h/s","20692.1h/s","21217.3h/s","20797.2h/s"],
    "ethinvalid":"0",
    "ethpoolsw":"0",
    "ethrejected":"0",
    "ethshares":"2",
    "fanpercentages":["66%","64%","70%","68%","66%","66%","74%","64%","70%","70%","66%","70%","70%","70%","70%","70%"],
    "pooladdrs":"us1.ethermine.org:4444",
    "powerusages":["73.6W","74.1W","74.6W","74.6W","74.2W","74.9W","74.6W","74.6W","74.8W","74.6W","74.4W","74.6W","74.7W","74.2W","73.6W","74.0W"],"runtime":"0","temperatures":["53C","52C","55C","54C","53C","53C","56C","52C","55C","55C","53C","55C","55C","55C","55C","55C"],
    "version":"0.14.0.dev1"
}

Let me know if you want to change something

### CODE REVIEW

**Comment by AndreaLanfranchi** [comment]
Could you please remove suffixes from values ?
And treat numbers without quotes. This would make life easier for parsers

Sent from mobile. Apologies for brevity and typos.



In data 18 febbraio 2018 22:15:57 David Solano <notifications@github.com> 
ha scritto:

**Comment by smurfy** [comment]
> Could you please remove suffixes from values ?

yea, second that.

**Comment by Davesmacer** [comment]
Got it

**Comment by Davesmacer** [comment]
Format change:

{
    "ethhashrate":216788.671875,
    "ethhashrates":[12313.072265625,20958.419921875,13230.0029296875,12968.0224609375,13099.0126953125,13360.9931640625,14408.9140625,13360.9931640625,12968.0224609375,11789.111328125,13360.9931640625,13753.962890625,12837.0322265625,11920.1005859375,13622.97265625,12837.0322265625],
    "ethinvalid":0,
    "ethpoolsw":0,
    "ethrejected":0,
    "ethshares":1,
    "fanpercentages":[64,62,70,66,64,64,70,62,68,68,64,70,70,68,68,68],
    "pooladdrs":"us1.ethermine.org:4444",
    "powerusages":[73.531999999999996,74.081999999999994,74.564999999999998,74.533000000000001,74.171999999999997,74.673000000000002,74.382000000000005,74.530000000000001,74.387,74.128,74.031999999999996,74.676000000000002,74.504999999999995,74.783000000000001,74.635999999999996,74.587999999999994],
    "runtime":"0",
    "temperatures":[52,51,55,53,52,52,55,51,55,54,52,55,55,55,54,54],
    "version":"0.14.0.dev1"
}

**Comment by Davesmacer** [comment]
It seems like last commit failed on a test.

It says something about apt not being able to fetch a repository data

Reading state information...
E: Unable to locate package cuda-core-9-0
E: Unable to locate package cuda-cudart-dev-9-0

Any ideas?

**Comment by AndreaLanfranchi** [comment]
If I may add just one more comment.
Why do you divide hashrates by 1000 ?
It would be better to have the hashrate value instead of kh or mh letting the parser decide which unit of measure to adopt.

**Comment by smurfy** [comment]
> Why do you divide hashrates by 1000

claymore returned it that way, but you are right, since this rpc method is not claymore, we can drop that.

**Comment by Davesmacer** [comment]
Hey guys! The last commit is returning h/s integer value as hashrate, as requested. Let me know of any more changes.

**Pull request merged**
