### PR TITLE
Added uptime to cli

### PR DESCRIPTION
**Pull request by smurfy**
This PR adds the current uptime in Hours+Minutes to the CLI.
API also uses the same info.

Closes: #301

### CODE REVIEW

**Comment by bmatthewshea** [comment]
Hi @smurfy @chfast - I notice the last few builds and new release 0.13 do not show the uptime/timer any longer? Seemed to have disappeared a few builds back (0.13.0rc5 iirc?). Can we please get this included? If I am missing a new flag/parameter to show it, or something just let me know..?

rel 0.13.0 - with `-HWMON ` 'on', but I see no 'running time' / 'uptime' output :
`m  08:35:19|main      Speed  23.61 Mh/s    gpu/0 23.61 64C 40%  [A137+1:R0+0:F0]`

Thanks much.

**Comment by jasonwee** [comment]
using 0.13, works for me, at the back
` m  12:43:21|ethminer-0.13.0  Speed  12.59 Mh/s    gpu/0 12.59 0C 0%  [A84+0:R0+0:F0] Time: 38:30`

**Comment by bmatthewshea** [comment]
I am using windows release build v13. I show the line I see. No time.

**Comment by bmatthewshea** [comment]
Seems to be different under Windows if using Cuda VS Opencl

**Pull request merged**
