### PR TITLE
Wrong order of comparison

### PR DESCRIPTION
**Pull request by AndreaLanfranchi**
Bad error in timeout comparison check.
Please merge urgently

### CODE REVIEW

**Comment by AndreaLanfranchi** [comment]
@chfast 
If it was included in 0.16.RC need to rebuild and publish new release

**Comment by jean-m-cyr** [comment]
@chfast Does not affect RC. Bug was added post RC.

**Comment by StefanOberhumer** [comment]
Shouldn't line 1550 (function EthStratumClient::dequeue_response_plea() )
also use `.load(...)` ?

> `steady_clock::time_point response_plea_time(m_response_plea_older);`

steady_clock::time_point response_plea_time(m_response_plea_older.load(std::memory_order_relaxed));

**Comment by AndreaLanfranchi** [comment]
Damn you're right !

**Pull request merged**
