### PR TITLE
MSVC: enable LTCG, RELEASE, OPT:REF,ICF.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by MariusVanDerWijden** [comment]
Can you write a description on what those flags do?

**Comment by XhmikosR** [comment]
You mean as a comment in the cmake file?

**Comment by MariusVanDerWijden** [comment]
no as a comment in here, so i don't have to look all of them up

**Comment by XhmikosR** [comment]
I added these switches to speed up the final executable as much as possible.

`OPT:REF` removes functions and data that are never referenced from the final executable.

See also the official docs for what they do exactly:

https://docs.microsoft.com/en-us/cpp/build/reference/gl-whole-program-optimization
https://docs.microsoft.com/en-us/cpp/build/reference/ltcg-link-time-code-generation
https://docs.microsoft.com/en-us/cpp/build/reference/opt-optimizations

`/RELEASE` is so that the final executable has its checksum set; that way one can easily check if the binary has been modified.

https://docs.microsoft.com/en-us/cpp/build/reference/release-set-the-checksum

I'm using a build with these switches already and works fine.

**Comment by MariusVanDerWijden** [comment]
> no as a comment in here, so i don't have to look all of them up
Can you please add it to the description to the file as well?
Do you have any statistics on how those changes impact the performance of the application?

**Comment by jean-m-cyr** [comment]
This is consistent with what we did for the gcc and clang builds a few weeks ago.

**Comment by XhmikosR** [comment]
@chfast : your 0.13.0 build doesn't seem to have been built at least with `/RELEASE` that I can quickly see. Which commit is it based off of?

**Comment by XhmikosR** [comment]
For some reason the 0.13.0 tag doesn't include this. It is included in master.

**Comment by XhmikosR** [comment]
OK, I see it now https://github.com/ethereum-mining/ethminer/compare/v0.13.0...master

**Pull request merged**
