### PR TITLE
Very basic implementation of return to primary pool.

### PR DESCRIPTION
**Pull request by AndreaLanfranchi**
In case we fall on a failover pool we can set an amount of time to stay there before trying to reconnect back to primary pool.

### CODE REVIEW

**Comment by AndreaLanfranchi** [comment]
@smurfy thank you.

Just added a trivial check. Could you please re-review ?

**Comment by smurfy** [comment]
only thing to possible add is, does it make sense to show a message, like
"Failover timeout reached, retrying primary pool"

**Comment by AndreaLanfranchi** [comment]
Of course. It does make sense.

**Comment by AndreaLanfranchi** [comment]
@smurfy : done !

**Pull request merged**
