### PR TITLE
Fix double disconnect()

### PR DESCRIPTION
**Pull request by chfast**

### CODE REVIEW

**Comment by AndreaLanfranchi** [comment]
IMHO I would leave disconnect() to be processed every time is invoked as it releases socket even if it's not connected. In fact m_connected.store is set only after successful connection but socket is created anyway.

**Comment by chfast** [comment]
Ok, sorry I didn't wait for you review.

This tries to workaround more complex problem to finally ship 0.14. When terminating the ethminer, the disconnect() can be called twice: one from regular shutdown, one from response read error. In the second case sockets are already destroyed and the ethminer crashes.

The bigger problem is that EthStratumClient is destroyed as well. So the read error handler operates on a corrupted object. EthStratumClient should be handled by a shared_ptr, but it's not. This definitely is fixable, but I'd like to keep the fixes for 0.14 minimal.

**Comment by AndreaLanfranchi** [comment]
I am working on addressing these problems on #1027 (some nonsenses already fixed) and working on a "real" async communication.
Probably you could check if you could merge into 0.14 too

**Comment by chfast** [comment]
Can you move your PR to be based on release/0.14 branch? I would need to rebase you commits and change the base branch in PR options. I can help with that if needed.

**Comment by AndreaLanfranchi** [comment]
Sure but have no idea how to do that ... can you give some hint ?

**Pull request merged**
