### PR TITLE
First pass on listing build requirements.

### LINKED ISSUE #1267: List build requirements in docs/BUILD.md
CMake version, Perl, GCC, MSVC, CUDA, etc

### PR DESCRIPTION
**Pull request by XhmikosR**
/CC @chfast @AndreaLanfranchi @jean-m-cyr 

Please fill in the info for OS'es apart from Windows. Also, I'm not sure if I should list Git as a requirement, i.e not sure if everything compiles from a source archive.

We should probably add a ToC too.

Fixes #1267

### CODE REVIEW

**Comment by jean-m-cyr** [comment]
GCC 4.7 was 1st to support C++11 required to build ethminer. That would be minimum GCC version.

**Comment by XhmikosR** [comment]
Please check out what else we need to list for Linux/macOS.

**Comment by AndreaLanfranchi** [comment]
I am a little concerned about OSX.
Aside from requirements we yet have a lot of issues complaining about strange hashrate reporting.

**Comment by chfast** [comment]
> Aside from requirements we yet have a lot of issues complaining about strange hashrate reporting.

Yep. Would be nice to find someone with macOS to help debugging these.

**Comment by XhmikosR** [comment]
I need some help with listing the requirements for macOS :)

**Comment by jean-m-cyr** [comment]
> Yep. Would be nice to find someone with macOS to help debugging these.

Alternatively, we could just drop MAC support. There is currently no way to mine Eth profitably on a MAC, and there doesn't seem to be much interest anyway!

**Comment by XhmikosR** [comment]
OK, I think we can merge; it looks good as a first step to me. Someone approve please.

**Comment by XhmikosR** [comment]
Forgot to ask, is Python needed for build?

**Comment by XhmikosR** [comment]
I don't even recall since I have Python 3.6 already installed on my dev VM :/

**Pull request merged**
