### PR TITLE
ProgPoW - MVDW

### PR DESCRIPTION
**Pull request by MariusVanDerWijden**
My attempt to add the ProgPoW algorithm alongside ethash into ethminer. 
Not Finished **Do not merge**

### CODE REVIEW

**Comment by naikmyeong** [comment]
@hackmod @chfast Please make a review for this PR

**Comment by MariusVanDerWijden** [comment]
It's far from finished. The progpow part is not working currently

**Comment by naikmyeong** [comment]
@MariusVanDerWijden Can you rebase on this PR? https://github.com/ethereum-mining/ethminer/pull/1766

**Comment by MariusVanDerWijden** [comment]
Will rebase and refactor

**Pull request closed without merging**
