### PR TITLE
Fix ethminer with Mesa/clover

### LINKED ISSUE #59: OpenCL fails on Mesa and R9 280X
Let's start with OpenCL 1.1 support.

OpenCL 1.1 doesn't actually support the 'static' storage class specifier and so running ethminer on Mesa results is a bunch of
`input.cl:114:1: error: OpenCL version 1.1 does not support the 'static' storage class specifier`
obviously with different line numbers. To fix that I used the solution from [cpp-ethereum issue #3020](https://github.com/ethereum/cpp-ethereum/issues/3020) , where @lvella cleverly figured out you could enable the specifier anyway by prepending
`#pragma OPENCL EXTENSION cl_clang_storage_class_specifiers : enable`
at the top of
`/libethash-cl/ethash_cl_miner_kernel.cl`
which still works with the latest git of ethminer.

With that out of the way, the issue I'm facing now is that I'm instead getting
`[OPENCL]:<unknown>:0:0: in function ethash_calculate_dag_item void (i32, %union.compute_hash_share addrspace(1)*, %union.compute_hash_share addrspace(1)*, i32): unsupported initializer for address space`

I have no clue what this means since I don't know more than incredibly basic OpenCL. Grepping the source tree reveals this line:
`./libethash-cl/ethash_cl_miner_kernel.cl:386:__kernel void ethash_calculate_dag_item(uint start, __global hash64_t const* g_light, __global hash64_t * g_dag, uint isolate)`
which I, again, have no clue what it actually does. I presume the solution to this one isn't as simple as adding a `#pragma` directive.

How do I proceed from here?

Sample benchmark run, including Ctrl+C at the end where the program simply stopped for several minutes:
`ethminer/build$ ./ethminer/ethminer -G -M`
`[OPENCL]:Found suitable OpenCL device [AMD TAHITI (DRM 2.48.0 / 4.9.0-3-amd64, LLVM 3.9.1)] with 3221225472 bytes of GPU memory`
`Benchmarking on platform: CL`
`Preparing DAG for block #0`
`Warming up...`
`  ℹ  03:06:46|openclminer0  set work; seed: #00000000, target:  #000000000000`
`  ℹ  03:06:46|openclminer0  Initialising miner...`
`[OPENCL]:Using platform: Clover`
`[OPENCL]:Using device: AMD TAHITI (DRM 2.48.0 / 4.9.0-3-amd64, LLVM 3.9.1)(OpenCL 1.1 Mesa 13.0.6)`
`[OPENCL]:<unknown>:0:0: in function ethash_calculate_dag_item void (i32, %union.compute_hash_share addrspace(1)*, %union.compute_hash_share addrspace(1)*, i32): unsupported initializer for address space`

`[OPENCL]:clEnqueueWriteBuffer(-38)`
`Trial 1... 0`
`Trial 2... 0`
`Trial 3... 0`
`Trial 4... 0`
`Trial 5... 0`
`^C`
`ethminer/build$`

Edit: Sorry, there's no simple way to prevent GitHub from butchering the formatting in the last code block.

### PR DESCRIPTION
**Pull request by EoD**
OpenCL version 1.1 does not support storage-class qualifiers and hence
does not work with current version of Mesa/clover.

The extension ``cl_clang_storage_class_specifiers`` allows the usage of
storage-class qualifiers with Mesa/clover.

Fixes #59

### CODE REVIEW

**Comment by EoD** [comment]
I rebased the branch on top of the current master and removed the restriction of OpenCL 1.2 for Clover.

**Comment by chfast** [comment]
Does it works with Clover now?

**Comment by EoD** [comment]
Yes, it works fine for me.

**Comment by Alpherie** [comment]
Despite error changed, it did not help on RX 460, still 0 Hashrate. 

```
./ethminer -M -G
[OpenCL] Found suitable OpenCL device [AMD POLARIS11 (DRM 3.8.0 / 4.9.0-3-amd64, LLVM 4.0.1)] with 4257992704 bytes of GPU memory
Benchmarking on platform: CL
Preparing DAG for block #0
Warming up...
  ℹ  13:04:21|openclminer0  set work; seed: #00000000, target:  #000000000000
  ℹ  13:04:21|openclminer0  Initialising miner...
[OpenCL] Platform: Clover
[OpenCL] Device:   AMD POLARIS11 (DRM 3.8.0 / 4.9.0-3-amd64, LLVM 4.0.1) / OpenCL 1.1 Mesa 17.1.2 (git-96c85d0a4c)
[OpenCL] OpenCL 1.1 not supported, but platform Clover might work nevertheless. USE AT OWN RISK!
[OpenCL] <unknown>:0:0: in function ethash_calculate_dag_item void (i32, %union.compute_hash_share addrspace(1)*, %union.compute_hash_share addrspace(1)*, i32): unsupported initializer for address space

[OpenCL] clEnqueueWriteBuffer(-38)
Trial 1... 0
Trial 2... 0
Trial 3... 0
Trial 4... 0
Trial 5... 0

```

**Comment by EoD** [comment]
@Alpherie I would consider reporting this upstream as it's identical to the error reported in #59. I can't reproduce this at all, but I am using newer software.

```
[OPENCL]:Using platform: Clover
[OPENCL]:Using device: AMD Radeon R9 380 Series (AMD TONGA / DRM 3.10.0 / 4.11.8, LLVM 3.9.1)(OpenCL 1.1 Mesa 17.2.0-devel (git-038c45a40e))
```

with the following hash rate
```
  m  09:09:52|ethminer  Mining on PoWhash #6c3c2e19 : 7.86MH/s [A0+0:R0+0:F0]
  m  09:09:52|ethminer  Mining on PoWhash #6c3c2e19 : 7.86MH/s [A0+0:R0+0:F0]
  m  09:09:52|ethminer  Mining on PoWhash #6c3c2e19 : 7.86MH/s [A0+0:R0+0:F0]
  m  09:09:53|ethminer  Mining on PoWhash #6c3c2e19 : 0.00MH/s [A0+0:R0+0:F0]
  m  09:09:53|ethminer  Mining on PoWhash #6c3c2e19 : 7.86MH/s [A0+0:R0+0:F0]
  m  09:09:53|ethminer  Mining on PoWhash #6c3c2e19 : 5.24MH/s [A0+0:R0+0:F0]
  m  09:09:53|ethminer  Mining on PoWhash #6c3c2e19 : 7.86MH/s [A0+0:R0+0:F0]
```

**Pull request merged**
