### PR TITLE
Updated CUDA for RTX architecture

### PR DESCRIPTION
**Pull request by MariusVanDerWijden**
Requires CUDA 10

### CODE REVIEW

**Comment by AndreaLanfranchi** [comment]
May it cause problem for CUDA 9 ? Or is it simply ignored ?

**Comment by MariusVanDerWijden** [comment]
It will cause problems on CUDA 9

**Comment by AndreaLanfranchi** [comment]
Yes it reports a fatal error.
We need to settle wether min CUDA supported version is 10

**Comment by MariusVanDerWijden** [comment]
I would not require it for at least two months, but this pr should exist for everyone with a new RTX card to test ethminer and report results

**Comment by AndreaLanfranchi** [comment]
Ok

**Comment by OhGodADog** [comment]
Just tried compiling with SM_75, and it worked, maybe already fixed?

**Comment by XhmikosR** [comment]
Don't we need to update cmake or hunter for this? I tried Cuda 10 with current master and it can't find the Cuda installation.

**Comment by XhmikosR** [comment]
Just tested CUDA 10: it needs cmake 3.12.2 and works with MSVC 2017 default compilers.

**Comment by OhGodADog** [comment]
> 
> 
> Don't we need to update cmake or hunter for this? I tried Cuda 10 with current master and it can't find the Cuda installation.
> 
> ```
> CMake Error at C:/Program Files/CMake/share/cmake-3.11/Modules/FindCUDA.cmake:687 (message):
>   Specify CUDA_TOOLKIT_ROOT_DIR
> ```
> 
> EDIT:
> 
> Just tested CUDA 10: it needs cmake 3.12.2 and works with MSVC 2017 default compilers.

I compiled it on Ubuntu 18, with the default CMake from the package manager, which is version 3.10.2

**Comment by XhmikosR** [comment]
Yeah, well, didn't work on Windows for me.

**Comment by chfast** [comment]
@XhmikosR The CMake searches for nvcc compiler. If it is in the PATH it will figure out the SDK path.

**Comment by XhmikosR** [comment]
Like I said, it does not work for CUDA 10 without updating cmake for me.

**Comment by chfast** [comment]
Done in #1614

**Pull request closed without merging**
