### PR TITLE
The last step of building from the source is actually `make`

### PR DESCRIPTION
**Pull request by amyodov**

### CODE REVIEW

**Comment by manpowre** [comment]
dont forget "sudo make install" on linux

**Comment by amyodov** [comment]
Cannot surely confirm about Linux, but on macOS, it works pretty well without `sudo make install`, just by running the generated binary from the build directory. But until `make` is done, no binary is available yet.

**Comment by chfast** [comment]
Well, the last one `cmake --build .` is the portable variant of `make` (it runs `make` effectively). The advantage of it is it will run Visual Studio build on Windows.

**Comment by amyodov** [comment]
Right, my fault. For some most weird reason I wasn't able to get the ethminer binary without `make` on my first try; but now, having rechecked it on a clean install, I see that `cmake --build .` indeed generates it.

**Pull request closed without merging**
