### PR TITLE
Include git branch and last commit in version info

### PR DESCRIPTION
**Pull request by jean-m-cyr**
Also get rid of some build warnings and Windows line endings in source

### CODE REVIEW

**Comment by jean-m-cyr** [comment]
Only works with local git repo. Doesn't work in continuous integration

**Comment by jean-m-cyr** [comment]
Closing

**Comment by piotr-dobrogost** [comment]
This would be very useful…

**Comment by smurfy** [comment]
Well the CI Servers provide different ENV Vars with similiar infos

``CIRCLE_SHA1`` , ``APPVEYOR_PULL_REQUEST_HEAD_COMMIT``, ``TRAVIS_PULL_REQUEST_SHA``

There are more, for branch/tag info depending on CI service

**Pull request closed without merging**
