### PR TITLE
Simplify log output

### PR DESCRIPTION
**Pull request by chfast**

### CODE REVIEW

**Comment by nikita3030678** [comment]
Log improvements work nicely, no more lag on Celeron CPU. Thank you.
Now testing with latest CUDA runtime 8.0.61.

**Comment by chfast** [comment]
Thanks @nikita3030678 for checking it out.

**Comment by ChronoXNL** [comment]
@chfast : Latest build seemed to have solved the issues for me on 2 machines. Tested with latest build #112.

Setup: 7 x 1070, celeron 3930, 8gb mem, z270a chipset.

**Comment by ksimic** [comment]
Issue still persists..

ethminer.exe -F http://dbix2.pool.sexy:7777/XXX -G
Found suitable OpenCL device [GeForce GTX 1080 Ti] with 11811160064 bytes of GPU memory
  m  12:13:08|main  Getting work package...
  m  12:13:08|main  Got work package: #3be17e8d
  i  12:13:08|openclminer0  set work; seed: #290decd9, target: #0000000225c1
  i  12:13:08|openclminer1  set work; seed: #290decd9, target: #0000000225c1
  i  12:13:08|openclminer0  Initialising miner...
  i  12:13:08|openclminer1  Initialising miner...
  i  12:13:08|openclminer2  set work; seed: #290decd9, target: #0000000225c1
  i  12:13:08|openclminer2  Initialising miner...
  i  12:13:08|openclminer3  set work; seed: #290decd9, target: #0000000225c1
  i  12:13:08|openclminer3  Initialising miner...
  i  12:13:08|openclminer4  set work; seed: #290decd9, target: #0000000225c1
  i  12:13:08|openclminer4  Initialising miner...
  i  12:13:08|openclminer5  set work; seed: #290decd9, target: #0000000225c1
  i  12:13:08|openclminer5  Initialising miner...

**Any line from here on does char by char output and 100% CPU usage, rendering ethminer unusable**

  m  12:13:09|main  Mining on PoWhash #3be17e8d : 0.00MH/s [A0+0:R0+0:F0]
Using platform: NVIDIA CUDA  m  12:13:10|main  M

the m lines are killing the system @chfast 

Looking at the code ETHCL_LOG still uses the spin lock based approach..

**Comment by chfast** [comment]
Check https://github.com/ethereum-mining/ethminer/pull/130.

**Pull request merged**
